const SUPABASE_URL='https://jqpxlbhwvskhjbqrbidk.supabase.co',SUPABASE_KEY='sb_publishable_aqx1Q36C3cznImJ5KMDk3w_I1uUTHQK',db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY),$=id=>document.getElementById(id);
const matchId=new URLSearchParams(location.search).get('id');
let profile,m,state,other,names={},channel,stream=null,pc=null,remoteStream=null;
let localReady=false,remoteReady=false,leaving=false,generation=1,lastSignal='START';
let pendingCandidates=[],readyTimer=null,reconnectTimer=null,statsTimer=null,rebuilding=false;
let lastVideoBytes=-1,videoStalls=0,selectedDarts=[],submitting=false;
const TARGETS=['20','19','18','17','16','15','B'];
const ICE={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302','stun:stun2.l.google.com:19302']}],iceCandidatePoolSize:10,bundlePolicy:'max-bundle'};
const isOfferer=()=>profile?.id===m?.player1_id;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function debug(extra=''){const e=$('webrtcDebug');if(!e)return;e.textContent=`VIDEO DEBUG • RT:${channel?'ON':'OFF'} | Local:${localReady?'YES':'NO'} | Remote:${remoteReady?'YES':'NO'} | Role:${isOfferer()?'OFFER':'ANSWER'} | Peer:${pc?.connectionState||'none'} | ICE:${pc?.iceConnectionState||'none'} | Signal:${pc?.signalingState||'none'} | Gen:${generation} | Last:${lastSignal}${extra?' | '+extra:''}`}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function markGlyph(n){const x=Math.max(0,Math.min(3,Number(n)||0));return x===0?'–':x===1?'╱':x===2?'×':'⊗'}
function emptyMarks(){return {'20':0,'19':0,'18':0,'17':0,'16':0,'15':0,'B':0}}
function labelDart(d){if(d.target==='MISS')return'MISS';const prefix=d.mult===1?'S':d.mult===2?'D':'T';return `${prefix}${d.target==='B'?'BULL':d.target}`}
async function loadState(){const{data,error}=await db.from('cricket_match_state').select('*').eq('match_id',matchId).maybeSingle();if(error)throw error;state=data||{match_id:matchId,player1_marks:emptyMarks(),player2_marks:emptyMarks()}}
function renderBoard(){if(!state)return;const a=state.player1_marks||emptyMarks(),b=state.player2_marks||emptyMarks();$('cricketBoard').innerHTML=TARGETS.map(t=>{const am=Number(a[t]||0),bm=Number(b[t]||0),closed=am>=3&&bm>=3;return `<div class="cricket-row${closed?' both-closed':''}"><div class="cricket-mark${am>=3?' closed':''}">${markGlyph(am)}</div><div class="cricket-target">${t==='B'?'BULL':t}</div><div class="cricket-mark${bm>=3?' closed':''}">${markGlyph(bm)}</div></div>`}).join('')}
function buildKeypad(){const host=$('cricketKeypad');host.innerHTML=TARGETS.map(t=>{if(t==='B')return `<div class="cricket-key-row bull"><div class="cricket-key-label">BULL</div><button class="outline cricket-hit" data-target="B" data-mult="1">S</button><button class="outline cricket-hit" data-target="B" data-mult="2">D</button></div>`;return `<div class="cricket-key-row"><div class="cricket-key-label">${t}</div><button class="outline cricket-hit" data-target="${t}" data-mult="1">S</button><button class="outline cricket-hit" data-target="${t}" data-mult="2">D</button><button class="outline cricket-hit" data-target="${t}" data-mult="3">T</button></div>`}).join('');host.querySelectorAll('.cricket-hit').forEach(b=>b.onclick=()=>addDart(b.dataset.target,Number(b.dataset.mult)))}
function addDart(target,mult){if(!canThrow()||selectedDarts.length>=3)return;selectedDarts.push({target,mult});renderEntry()}
function canThrow(){return !!m&&m.status==='playing'&&m.turn_player_id===profile?.id&&!submitting}
function renderEntry(){const host=$('cricketDarts');const items=selectedDarts.map(d=>`<span class="cricket-dart">${esc(labelDart(d))}</span>`);while(items.length<3)items.push('<span class="cricket-dart empty">–</span>');host.innerHTML=items.join('');const enabled=canThrow();document.querySelectorAll('.cricket-hit').forEach(b=>b.disabled=!enabled||selectedDarts.length>=3);$('cricketMissBtn').disabled=!enabled||selectedDarts.length>=3;$('cricketUndoBtn').disabled=!enabled||!selectedDarts.length;$('cricketSubmitBtn').disabled=!enabled||!selectedDarts.length}
function render(){if(!m)return;$('cricketName1').textContent=names[m.player1_id]||'Spiller 1';$('cricketName2').textContent=names[m.player2_id]||'Spiller 2';$('cricketPoints1').textContent=String(m.player1_score||0);$('cricketPoints2').textContent=String(m.player2_score||0);$('cricketLegs1').textContent=`${m.player1_legs||0} legs`;$('cricketLegs2').textContent=`${m.player2_legs||0} legs`;$('cricketP1').classList.toggle('active',m.turn_player_id===m.player1_id&&m.status==='playing');$('cricketP2').classList.toggle('active',m.turn_player_id===m.player2_id&&m.status==='playing');const mine=m.turn_player_id===profile?.id&&m.status==='playing';$('videoGrid')?.classList.toggle('opponent-throwing',m.status==='playing'&&!mine);$('turnText').textContent=m.status==='cancelled'?'Kampen er avbrutt.':m.status==='finished'?`${names[m.winner_id]||'Vinner'} vant kampen.`:mine?'Din tur':`${names[m.turn_player_id]||'Motstanderen'} kaster`;$('matchStatus').textContent=m.status==='playing'?'Pågår':m.status==='finished'?'Ferdig':'Avbrutt';$('cancelMatchBtn').classList.toggle('hidden',m.status!=='playing');renderBoard();renderEntry()}
async function refreshGame(){const[{data:mm,error:me}]=await Promise.all([db.from('matches').select('*').eq('id',matchId).single(),loadState()]);if(me)throw me;m=mm;render()}
async function submitVisit(){if(!canThrow()||!selectedDarts.length)return;submitting=true;renderEntry();$('matchMessage').textContent='Registrerer…';try{const darts=selectedDarts.map(d=>({...d}));const{data,error}=await db.rpc('submit_cricket_visit',{p_match_id:matchId,p_darts:darts});if(error)throw error;selectedDarts=[];await refreshGame();$('matchMessage').textContent=data?.leg_won?(m.status==='finished'?'Kampen er vunnet!':'Leg vunnet!'):(Number(data?.points_scored||0)>0?`+${data.points_scored} poeng`:'');if(m.status==='finished')await setPlayersUnavailable()}catch(error){$('matchMessage').textContent=String(error?.message||'Kunne ikke registrere kastet.').replace('It is not your turn','Det er ikke din tur.')}finally{submitting=false;renderEntry()}}
$('cricketMissBtn').onclick=()=>addDart('MISS',0);$('cricketUndoBtn').onclick=()=>{selectedDarts.pop();renderEntry()};$('cricketSubmitBtn').onclick=submitVisit;

(async()=>{const{data:{session}}=await db.auth.getSession();if(!session||!matchId)return location.replace('./');({data:profile}=await db.from('profiles').select('*').eq('id',session.user.id).single());const{data,error}=await db.from('matches').select('*').eq('id',matchId).single();m=data;if(error||!m||![m.player1_id,m.player2_id].includes(profile.id))return location.replace('./');if(m.game_variant!=='cricket')return location.replace(`match.html?id=${encodeURIComponent(matchId)}`);other=profile.id===m.player1_id?m.player2_id:m.player1_id;const{data:p}=await db.from('profiles').select('id,username').in('id',[m.player1_id,m.player2_id]);names=Object.fromEntries((p||[]).map(x=>[x.id,x.username]));$('localVideoName').textContent=names[profile.id]||'Spiller';$('remoteVideoName').textContent=names[other]||'Spiller';$('matchTitle').textContent=`${names[m.player1_id]||'Spiller 1'} vs ${names[m.player2_id]||'Spiller 2'}`;$('matchFormat').textContent=`CRICKET • BEST OF ${m.legs}`;buildKeypad();await loadState();render();setupChannel()})().catch(e=>{$('matchMessage').textContent=e?.message||'Kunne ikke starte Cricket-kampen.'});

function setupChannel(){channel=db.channel('match-'+m.id)
.on('postgres_changes',{event:'UPDATE',schema:'public',table:'matches',filter:`id=eq.${m.id}`},async p=>{const oldLeg=m?.current_leg;m=p.new;if(oldLeg!==m.current_leg)selectedDarts=[];try{await loadState()}catch{}render();if(m.status!=='playing')await setPlayersUnavailable()})
.on('broadcast',{event:'ready'},async({payload})=>{if(payload.from!==other)return;remoteReady=true;lastSignal='READY received';debug();if(isOfferer())await connectIfReady()})
.on('broadcast',{event:'signal'},async({payload})=>{if(payload.from!==other)return;remoteReady=true;await handleSignal(payload)})
.on('broadcast',{event:'reconnect-request'},async({payload})=>{if(payload.from!==other||!isOfferer()||leaving)return;await rebuildAsOfferer('remote-request')})
.subscribe(async s=>{lastSignal=`RT ${s}`;debug();if(s==='SUBSCRIBED'){await startCamera();startReadyHeartbeat()}})}
function startReadyHeartbeat(){clearInterval(readyTimer);readyTimer=setInterval(()=>{if(!leaving&&localReady)send('ready',{generation})},2500)}
function cameraErrorText(e){if(e?.name==='NotAllowedError')return'Kamera/mikrofon er blokkert i nettleseren.';if(e?.name==='NotFoundError')return'Fant ikke kamera eller mikrofon.';if(e?.name==='NotReadableError')return'Kameraet kan være i bruk av et annet program.';return`Kamera kunne ikke startes${e?.name?' ('+e.name+')':''}.`}
async function startCamera(){if(stream?.active){localReady=true;await send('ready',{generation});if(isOfferer())await connectIfReady();return}try{stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const v=$('localVideo');v.srcObject=stream;v.muted=true;await v.play().catch(()=>{});$('localPlaceholder').classList.add('hidden');$('cameraBtn').textContent='Stopp kamera';localReady=true;lastSignal='CAMERA ready';debug();await send('ready',{generation});if(isOfferer())await connectIfReady()}catch(e){localReady=false;$('localPlaceholder').classList.remove('hidden');$('localPlaceholder').textContent=cameraErrorText(e);$('matchMessage').textContent=cameraErrorText(e);lastSignal=`CAMERA ${e?.name||'error'}`;debug()}}
function showRemotePlaceholder(text){const p=$('remotePlaceholder');if(p){p.textContent=text;p.classList.remove('hidden')}}
function hideRemotePlaceholder(){$('remotePlaceholder')?.classList.add('hidden')}
function clearPeer(){clearTimeout(reconnectTimer);reconnectTimer=null;clearInterval(statsTimer);statsTimer=null;pendingCandidates=[];lastVideoBytes=-1;videoStalls=0;if(pc){pc.ontrack=pc.onicecandidate=pc.onconnectionstatechange=pc.oniceconnectionstatechange=null;try{pc.close()}catch{}}pc=null;remoteStream=null;const v=$('remoteVideo');if(v){v.pause?.();v.srcObject=null}showRemotePlaceholder('Kobler til video…')}
function attachRemoteTrack(e,myGen,p){if(p!==pc||myGen!==generation)return;if(!remoteStream)remoteStream=new MediaStream();const t=e.track;if(!remoteStream.getTracks().some(x=>x.id===t.id))remoteStream.addTrack(t);const v=$('remoteVideo');v.srcObject=remoteStream;lastSignal=`TRACK ${t.kind}`;if(t.kind==='video'){const play=async()=>{if(p!==pc||myGen!==generation)return;try{v.muted=true;await v.play();hideRemotePlaceholder()}catch{showRemotePlaceholder('Klikk i siden for å starte video')}};t.onunmute=play;t.onended=()=>requestRecovery('remote-track-ended');v.onloadedmetadata=play;v.oncanplay=play;play()}debug()}
function createPeer(){if(pc||!stream?.active)return pc;const myGen=generation,p=new RTCPeerConnection(ICE);pc=p;remoteStream=new MediaStream();$('remoteVideo').srcObject=remoteStream;for(const t of stream.getTracks())p.addTrack(t,stream);p.ontrack=e=>attachRemoteTrack(e,myGen,p);p.onicecandidate=e=>{if(p!==pc||myGen!==generation||!e.candidate)return;send('signal',{candidate:e.candidate.toJSON?e.candidate.toJSON():e.candidate,generation:myGen});lastSignal='ICE sent';debug()};p.oniceconnectionstatechange=()=>{if(p!==pc)return;lastSignal=`ICE ${p.iceConnectionState}`;debug();if(p.iceConnectionState==='failed')requestRecovery('ice-failed')};p.onconnectionstatechange=()=>{if(p!==pc)return;lastSignal=`PEER ${p.connectionState}`;debug();if(p.connectionState==='connected'){clearTimeout(reconnectTimer);reconnectTimer=null;startStatsWatch(p,myGen)}else if(p.connectionState==='disconnected')scheduleRecovery(5000,'peer-disconnected');else if(p.connectionState==='failed')requestRecovery('peer-failed')};return p}
async function connectIfReady(){if(leaving||rebuilding||!isOfferer()||!localReady||!remoteReady||!stream?.active)return;const p=createPeer();if(!p||p.signalingState!=='stable'||p.localDescription)return;try{const offer=await p.createOffer();if(p!==pc)return;await p.setLocalDescription(offer);lastSignal='OFFER sent';debug();await send('signal',{description:p.localDescription.toJSON?p.localDescription.toJSON():p.localDescription,generation})}catch(e){lastSignal=`OFFER ${e?.name||'error'}`;debug();scheduleRecovery(1200,'offer-error')}}
async function handleSignal(s){if(leaving||!localReady||!stream?.active)return;const sg=Number(s.generation)||1;if(sg<generation)return;if(s.description?.type==='offer'){if(isOfferer())return;if(sg>generation||pc){generation=sg;clearPeer()}const p=createPeer();if(!p)return;try{await p.setRemoteDescription(s.description);await flushCandidates(p);const answer=await p.createAnswer();if(p!==pc)return;await p.setLocalDescription(answer);lastSignal='ANSWER sent';debug();await send('signal',{description:p.localDescription.toJSON?p.localDescription.toJSON():p.localDescription,generation})}catch(e){lastSignal=`ANSWER ${e?.name||'error'}`;debug();requestRecovery('answer-error')}return}if(sg>generation){generation=sg;clearPeer()}const p=createPeer();if(!p)return;try{if(s.description?.type==='answer'){if(!isOfferer()||p.signalingState!=='have-local-offer')return;await p.setRemoteDescription(s.description);await flushCandidates(p);lastSignal='ANSWER set';debug()}else if(s.candidate){if(p.remoteDescription)await p.addIceCandidate(s.candidate);else pendingCandidates.push(s.candidate);lastSignal=p.remoteDescription?'ICE added':'ICE queued';debug()}}catch(e){lastSignal=`SIGNAL ${e?.name||'error'}`;debug();requestRecovery('signal-error')}}
async function flushCandidates(p){while(pendingCandidates.length&&p===pc&&p.remoteDescription){try{await p.addIceCandidate(pendingCandidates.shift())}catch{}}}
function startStatsWatch(p,myGen){clearInterval(statsTimer);lastVideoBytes=-1;videoStalls=0;statsTimer=setInterval(async()=>{if(leaving||p!==pc||myGen!==generation||p.connectionState!=='connected')return;try{const stats=await p.getStats();let bytes=0,frames=0,found=false;stats.forEach(r=>{if(r.type==='inbound-rtp'&&r.kind==='video'&&!r.isRemote){found=true;bytes+=Number(r.bytesReceived||0);frames+=Number(r.framesDecoded||0)}});if(!found)return;if(bytes>lastVideoBytes){lastVideoBytes=bytes;videoStalls=0;lastSignal=`VIDEO ${Math.round(bytes/1024)}KB/${frames}f`;hideRemotePlaceholder();debug()}else if(lastVideoBytes>=0){videoStalls++;lastSignal=`VIDEO stall ${videoStalls}/8`;debug();if(videoStalls>=8)requestRecovery('video-stalled')}}catch{}},1000)}
function scheduleRecovery(ms,reason){if(leaving||rebuilding||reconnectTimer)return;reconnectTimer=setTimeout(()=>{reconnectTimer=null;requestRecovery(reason)},ms)}
async function requestRecovery(reason){if(leaving||rebuilding)return;if(isOfferer())return rebuildAsOfferer(reason);lastSignal=`RECOVERY request ${reason}`;debug();await send('reconnect-request',{reason,generation});showRemotePlaceholder('Gjenoppretter video…')}
async function rebuildAsOfferer(reason){if(leaving||rebuilding||!isOfferer())return;rebuilding=true;generation+=1;lastSignal=`REBUILD ${reason}`;debug();clearPeer();showRemotePlaceholder('Gjenoppretter video…');await sleep(300);rebuilding=false;await send('ready',{generation});await connectIfReady()}
async function send(event,payload={}){if(channel)await channel.send({type:'broadcast',event,payload:{...payload,from:profile.id}})}
$('cameraBtn').onclick=async()=>{if(!stream)return startCamera();localReady=false;stream.getTracks().forEach(t=>t.stop());stream=null;clearPeer();$('localVideo').srcObject=null;$('localPlaceholder').classList.remove('hidden');showRemotePlaceholder('Venter på motstanderens kamera…');$('cameraBtn').textContent='Start kamera';lastSignal='CAMERA stopped';debug()};
async function setPlayersUnavailable(){if(m)await db.from('profiles').update({status:'unavailable'}).in('id',[m.player1_id,m.player2_id])}
function closeMatchTab(){cleanup();window.close();setTimeout(()=>{if(!window.closed){document.body.innerHTML='<main class="shell"><section class="card" style="max-width:520px;margin:10vh auto;text-align:center"><h2>Kampen er avbrutt</h2><p class="muted">Denne kampfanen kan nå lukkes.</p><button class="primary" onclick="window.close()">Lukk fane</button></section></main>'}},150)}
$('cancelMatchBtn').onclick=async()=>{if(!m||m.status!=='playing'||!confirm('Vil du avbryte kampen?'))return;const{error}=await db.from('matches').update({status:'cancelled',finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',m.id);if(error)return $('matchMessage').textContent='Kunne ikke avbryte: '+error.message;await setPlayersUnavailable();window.opener?.postMessage({type:'dartarena-match-ended',id:m.id},location.origin);closeMatchTab()};
$('closeMatchBtn').onclick=()=>{if(m?.status==='playing'&&!confirm('Kampen pågår fortsatt. Du kan åpne den igjen fra lobbyen. Lukk kampfanen?'))return;window.close();if(!window.closed)location.href='./'};
function cleanup(){leaving=true;localReady=false;clearInterval(readyTimer);readyTimer=null;clearInterval(statsTimer);statsTimer=null;clearTimeout(reconnectTimer);reconnectTimer=null;stream?.getTracks().forEach(t=>t.stop());stream=null;clearPeer();if(channel)db.removeChannel(channel)}
window.addEventListener('beforeunload',cleanup);