const SUPABASE_URL='https://jqpxlbhwvskhjbqrbidk.supabase.co',SUPABASE_KEY='sb_publishable_aqx1Q36C3cznImJ5KMDk3w_I1uUTHQK',db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY),$=id=>document.getElementById(id);
const matchId=new URLSearchParams(location.search).get('id');
const BOARD=[20,1,18,4,13,6,10,15,2,17,3,19,7,16,8,11,14,9,12,5];
const ROUNDS=[
  {type:'number',target:20,label:'20',history:'20',help:'Tre piler på 20. Single, double og treble teller normal verdi.'},
  {type:'double',label:'Double',history:'Double',help:'Tre piler. Alle doubler teller sin normale verdi.'},
  {type:'number',target:19,label:'19',history:'19',help:'Tre piler på 19. Single, double og treble teller normal verdi.'},
  {type:'treble',label:'Treble',history:'Treble',help:'Tre piler. Alle trebler teller sin normale verdi.'},
  {type:'number',target:18,label:'18',history:'18',help:'Tre piler på 18. Single, double og treble teller normal verdi.'},
  {type:'different',label:'3 forskjellige farger',history:'3 forskjellige farger',help:'Alle tre pilene må lande i tre forskjellige dartboard-farger. Da teller summen av alle tre.'},
  {type:'number',target:17,label:'17',history:'17',help:'Tre piler på 17. Single, double og treble teller normal verdi.'},
  {type:'exact',label:'Eksakt score',history:'Eksakt score',help:'Tre piler skal gi nøyaktig totalscoren som vises.'},
  {type:'number',target:16,label:'16',history:'16',help:'Tre piler på 16. Single, double og treble teller normal verdi.'},
  {type:'same',label:'Samme farge',history:'Samme farge',help:'Alle tre pilene må lande i samme dartboard-farge. Da teller summen av alle tre.'},
  {type:'number',target:15,label:'15',history:'15',help:'Tre piler på 15. Single, double og treble teller normal verdi.'},
  {type:'bull',label:'Bull',history:'Bull',help:'Tre piler på bull. Outer bull gir 25 og bullseye 50.'}
];
let profile,m,state,visits=[],other,names={},channel,stream=null,publisherSfu=null,subscriberSfu=null,publication=null,publicationTimer=null,remotePublicationId=null,remoteStream=null,selectedDarts=[],selectedMult=1,submitting=false,leaving=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roundCount=playerId=>visits.filter(v=>v.player_id===playerId).length;
const nextRound=playerId=>Math.min(12,roundCount(playerId)+1);
const canThrow=()=>!!m&&m.status==='playing'&&m.turn_player_id===profile?.id&&!submitting;
function dartValue(d){return d.n===25?25*d.mult:d.n*d.mult}
function dartColor(d){if(!d||d.n===0)return'miss';if(d.n===25)return d.mult===1?'green':'red';const idx=BOARD.indexOf(d.n);if(idx<0)return'?';if(d.mult===1)return idx%2===0?'black':'white';return idx%2===0?'red':'green'}
function colorLabel(c){return({black:'SORT',white:'HVIT',red:'RØD',green:'GRØNN',miss:'MISS'})[c]||c.toUpperCase()}
function dartLabel(d){if(!d||d.n===0)return'MISS';if(d.n===25)return d.mult===1?'25':'50';return`${d.mult===1?'S':d.mult===2?'D':'T'}${d.n}`}
function addDart(n,mult){if(!canThrow()||selectedDarts.length>=3)return;if(n===25&&mult===3)return;selectedDarts.push({n:Number(n),mult:Number(mult)});renderEntry()}
function currentRoundNo(){if(!m)return 1;if(m.status!=='playing')return 12;return nextRound(m.turn_player_id)}
function currentRound(){return ROUNDS[currentRoundNo()-1]||ROUNDS[11]}
function roundDisplay(roundNo){const r=ROUNDS[roundNo-1];if(!r)return'';if(r.type==='exact'&&state?.exact_target)return`Eksakt ${state.exact_target}`;return r.history}
function buildPad(){const host=$('halfPad');if(!host)return;const r=currentRound(),enabled=canThrow()&&selectedDarts.length<3;if(!r||m?.status!=='playing'){host.innerHTML='';return}
  if(r.type==='number'){
    host.innerHTML=`<div class="half-quick"><button class="outline half-hit" data-n="${r.target}" data-mult="1">S${r.target}</button><button class="outline half-hit" data-n="${r.target}" data-mult="2">D${r.target}</button><button class="outline half-hit" data-n="${r.target}" data-mult="3">T${r.target}</button></div>`;
  }else if(r.type==='bull'){
    host.innerHTML='<div class="half-quick"><button class="outline half-hit" data-n="25" data-mult="1">25</button><button class="outline half-hit" data-n="25" data-mult="2">50</button></div>';
  }else if(r.type==='double'||r.type==='treble'){
    const mult=r.type==='double'?2:3,nums=Array.from({length:20},(_,i)=>i+1),bull=r.type==='double'?'<button class="outline half-hit" data-n="25" data-mult="2">DB</button>':'';
    host.innerHTML=`<div class="half-number-grid">${nums.map(n=>`<button class="outline half-hit" data-n="${n}" data-mult="${mult}">${mult===2?'D':'T'}${n}</button>`).join('')}${bull}</div>`;
  }else{
    const nums=Array.from({length:20},(_,i)=>i+1);
    host.innerHTML=`<div class="half-multiplier"><button class="outline half-mult ${selectedMult===1?'active':''}" data-mult="1">SINGLE</button><button class="outline half-mult ${selectedMult===2?'active':''}" data-mult="2">DOUBLE</button><button class="outline half-mult ${selectedMult===3?'active':''}" data-mult="3">TREBLE</button></div><div class="half-number-grid">${nums.map(n=>`<button class="outline half-hit" data-n="${n}" data-mult="${selectedMult}">${selectedMult===1?'S':selectedMult===2?'D':'T'}${n}</button>`).join('')}<button class="outline half-hit" data-n="25" data-mult="${selectedMult}" ${selectedMult===3?'disabled':''}>${selectedMult===1?'25':selectedMult===2?'50':'BULL'}</button></div>`;
  }
  host.querySelectorAll('.half-hit').forEach(b=>{b.disabled=b.disabled||!enabled;b.onclick=()=>addDart(Number(b.dataset.n),Number(b.dataset.mult))});
  host.querySelectorAll('.half-mult').forEach(b=>{b.disabled=!enabled;b.onclick=()=>{selectedMult=Number(b.dataset.mult);buildPad()}});
}
function renderEntry(){const items=selectedDarts.map(d=>`<div class="half-dart">${esc(dartLabel(d))}<small style="display:block;color:var(--muted);font-size:9px;margin-top:2px">${esc(colorLabel(dartColor(d)))}</small></div>`);while(items.length<3)items.push('<div class="half-dart empty">–</div>');$('halfDarts').innerHTML=items.join('');const enabled=canThrow();$('halfMissBtn').disabled=!enabled||selectedDarts.length>=3;$('halfUndoBtn').disabled=!enabled||!selectedDarts.length;$('halfSubmitBtn').disabled=!enabled||selectedDarts.length!==3;buildPad()}
function renderHistory(){const body=$('halfHistoryBody');if(!body||!m)return;const active=currentRoundNo();body.innerHTML=ROUNDS.map((r,i)=>{const rn=i+1,a=visits.find(v=>v.player_id===m.player1_id&&v.round_no===rn),b=visits.find(v=>v.player_id===m.player2_id&&v.round_no===rn),label=r.type==='exact'&&(a||b||active>=8)&&state?.exact_target?`Eksakt ${state.exact_target}`:r.history;return`<tr class="${m.status==='playing'&&rn===active?'current':''}"><td>${rn}. ${esc(label)}</td><td>${a?Number(a.score_after):'–'}</td><td>${b?Number(b.score_after):'–'}</td></tr>`}).join('')}
function render(){if(!m||!profile)return;const c1=roundCount(m.player1_id),c2=roundCount(m.player2_id),mine=m.turn_player_id===profile.id&&m.status==='playing',rn=currentRoundNo(),r=currentRound();$('halfName1').textContent=names[m.player1_id]||'Spiller 1';$('halfName2').textContent=names[m.player2_id]||'Spiller 2';$('historyName1').textContent=names[m.player1_id]||'Spiller 1';$('historyName2').textContent=names[m.player2_id]||'Spiller 2';$('halfScore1').textContent=String(m.player1_score||0);$('halfScore2').textContent=String(m.player2_score||0);$('halfRound1').textContent=c1>=12?'12/12 ferdig':`Runde ${c1+1}/12`;$('halfRound2').textContent=c2>=12?'12/12 ferdig':`Runde ${c2+1}/12`;$('halfP1').classList.toggle('active',m.status==='playing'&&m.turn_player_id===m.player1_id);$('halfP2').classList.toggle('active',m.status==='playing'&&m.turn_player_id===m.player2_id);$('videoGrid')?.classList.toggle('opponent-throwing',m.status==='playing'&&!mine);
  if(m.status==='finished'){$('halfRoundLabel').textContent='FERDIG';$('halfTarget').textContent=m.winner_id?`${names[m.winner_id]||'Vinner'} vant`:'Uavgjort';$('halfHelp').textContent=`Sluttscore ${m.player1_score} – ${m.player2_score}.`;$('turnText').textContent=m.winner_id?`${names[m.winner_id]||'Vinner'} vant`:'Uavgjort';$('matchStatus').textContent='Ferdig'}
  else if(m.status==='cancelled'){$('halfRoundLabel').textContent='AVBRUTT';$('halfTarget').textContent='Kampen er avbrutt';$('halfHelp').textContent='';$('turnText').textContent='Avbrutt';$('matchStatus').textContent='Avbrutt'}
  else{$('halfRoundLabel').textContent=`RUNDE ${rn} AV 12`;$('halfTarget').textContent=r.type==='exact'&&state?.exact_target?`Eksakt ${state.exact_target}`:r.label;$('halfHelp').textContent=r.help;$('turnText').textContent=mine?'Din tur':`${names[m.turn_player_id]||'Motstanderen'} kaster`;$('matchStatus').textContent='Pågår'}
  const revealExact=m.status!=='playing'||rn>=8||visits.some(v=>v.round_no>=8);$('exactTarget').textContent=revealExact&&state?.exact_target?String(state.exact_target):'Vises i runde 8';$('cancelMatchBtn').classList.toggle('hidden',m.status!=='playing');renderEntry();renderHistory()}
async function refreshGame(){const[{data:mm,error:me},{data:ss,error:se},{data:vv,error:ve}]=await Promise.all([db.from('matches').select('*').eq('id',matchId).single(),db.from('half_it_match_state').select('*').eq('match_id',matchId).single(),db.from('half_it_visits').select('*').eq('match_id',matchId).order('round_no').order('id')]);if(me)throw me;if(se)throw se;if(ve)throw ve;m=mm;state=ss;visits=vv||[];render()}
async function submitRound(){if(!canThrow()||selectedDarts.length!==3)return;submitting=true;renderEntry();$('matchMessage').textContent='Registrerer…';try{const darts=selectedDarts.map(d=>({...d})),{data,error}=await db.rpc('submit_half_it_visit',{p_match_id:matchId,p_darts:darts});if(error)throw error;selectedDarts=[];selectedMult=1;await refreshGame();$('matchMessage').textContent=data?.success?`+${Number(data.points_scored||0)} poeng`:`Score halvert til ${Number(data?.score_after||0)}`;if(m.status==='finished')await setPlayersUnavailable()}catch(e){$('matchMessage').textContent=String(e?.message||'Kunne ikke registrere runden.').replace('It is not your turn','Det er ikke din tur.')}finally{submitting=false;renderEntry()}}
$('halfMissBtn').onclick=()=>addDart(0,0);$('halfUndoBtn').onclick=()=>{selectedDarts.pop();renderEntry()};$('halfSubmitBtn').onclick=submitRound;

(async()=>{const{data:{session}}=await db.auth.getSession();if(!session||!matchId)return location.replace('./');({data:profile}=await db.from('profiles').select('*').eq('id',session.user.id).single());const{data,error}=await db.from('matches').select('*').eq('id',matchId).single();m=data;if(error||!m||![m.player1_id,m.player2_id].includes(profile.id))return location.replace('./');if(m.game_variant!=='half_it')return location.replace(m.game_variant==='cricket'?`cricket.html?id=${encodeURIComponent(matchId)}`:`match.html?id=${encodeURIComponent(matchId)}`);other=profile.id===m.player1_id?m.player2_id:m.player1_id;const{data:p}=await db.from('profiles').select('id,username').in('id',[m.player1_id,m.player2_id]);names=Object.fromEntries((p||[]).map(x=>[x.id,x.username]));$('localVideoName').textContent=names[profile.id]||'Spiller';$('remoteVideoName').textContent=names[other]||'Spiller';$('matchTitle').textContent=`${names[m.player1_id]||'Spiller 1'} vs ${names[m.player2_id]||'Spiller 2'}`;await refreshGame();setupChannel()})().catch(e=>{$('matchMessage').textContent=e?.message||'Kunne ikke starte Half-It-kampen.'});

function setupChannel(){channel=db.channel('half-it-'+matchId).on('postgres_changes',{event:'UPDATE',schema:'public',table:'matches',filter:`id=eq.${matchId}`},async()=>{try{await refreshGame();if(m.status!=='playing')await setPlayersUnavailable()}catch(e){console.error(e)}}).on('broadcast',{event:'half-it-publication'},async({payload})=>{if(payload.from!==other||!payload.publication)return;await subscribeRemote(payload.publication)}).on('broadcast',{event:'half-it-camera-off'},({payload})=>{if(payload.from!==other)return;remotePublicationId=null;subscriberSfu?.close();subscriberSfu=null;remoteStream=null;const v=$('remoteVideo');v.pause?.();v.srcObject=null;$('remotePlaceholder').textContent='Motstanderens kamera er av';$('remotePlaceholder').classList.remove('hidden')}).subscribe(async status=>{if(status==='SUBSCRIBED')await startCamera()})}
async function send(event,payload={}){if(channel)await channel.send({type:'broadcast',event,payload:{...payload,from:profile.id}})}
async function startCamera(){if(stream?.active&&publication){await send('half-it-publication',{publication});return}try{stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const v=$('localVideo');v.srcObject=stream;v.muted=true;await v.play().catch(()=>{});$('localPlaceholder').classList.add('hidden');$('cameraBtn').textContent='Stopp kamera';publisherSfu?.close();publisherSfu=new DartArenaSFU(window.DARTARENA_SFU.workerUrl);publication=await publisherSfu.publish(stream);await send('half-it-publication',{publication});clearInterval(publicationTimer);publicationTimer=setInterval(()=>{if(publication&&!leaving)send('half-it-publication',{publication})},2500)}catch(e){stream?.getTracks?.().forEach(t=>t.stop());stream=null;publication=null;$('localPlaceholder').textContent='Kamera kunne ikke startes';$('localPlaceholder').classList.remove('hidden');$('matchMessage').textContent=e?.message||'Kamera kunne ikke startes';$('cameraBtn').textContent='Start kamera'}}
async function subscribeRemote(pub){if(!pub?.sessionId||pub.sessionId===remotePublicationId)return;remotePublicationId=pub.sessionId;try{subscriberSfu?.close();subscriberSfu=new DartArenaSFU(window.DARTARENA_SFU.workerUrl);remoteStream=new MediaStream();const v=$('remoteVideo');v.srcObject=remoteStream;v.muted=true;await subscriberSfu.subscribe(pub,e=>{const tracks=e.streams?.[0]?.getTracks()||[e.track];for(const t of tracks)if(!remoteStream.getTracks().some(x=>x.id===t.id))remoteStream.addTrack(t);v.srcObject=remoteStream;v.play().catch(()=>{});if(remoteStream.getVideoTracks().some(t=>t.readyState==='live'))$('remotePlaceholder').classList.add('hidden')});}catch(e){remotePublicationId=null;$('remotePlaceholder').textContent='Kobler til motstanderens kamera…';$('remotePlaceholder').classList.remove('hidden');console.warn('Half-It remote video failed',e)}}
$('cameraBtn').onclick=async()=>{if(!stream)return startCamera();clearInterval(publicationTimer);publicationTimer=null;publication=null;publisherSfu?.close();publisherSfu=null;stream.getTracks().forEach(t=>t.stop());stream=null;$('localVideo').srcObject=null;$('localPlaceholder').textContent='Ditt kamera';$('localPlaceholder').classList.remove('hidden');$('cameraBtn').textContent='Start kamera';await send('half-it-camera-off')};
async function setPlayersUnavailable(){if(m)await db.from('profiles').update({status:'unavailable'}).in('id',[m.player1_id,m.player2_id])}
function closeMatchTab(){cleanup();window.close();setTimeout(()=>{if(!window.closed){document.body.innerHTML='<main class="shell"><section class="card" style="max-width:520px;margin:10vh auto;text-align:center"><h2>Kampen er avsluttet</h2><p class="muted">Denne kampfanen kan nå lukkes.</p><button class="primary" onclick="window.close()">Lukk fane</button></section></main>'}},150)}
$('cancelMatchBtn').onclick=async()=>{if(!m||m.status!=='playing'||!confirm('Vil du avbryte kampen?'))return;const b=$('cancelMatchBtn');b.disabled=true;b.textContent='Avbryter…';const{error}=await db.from('matches').update({status:'cancelled',finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',m.id);if(error){b.disabled=false;b.textContent='Avbryt kamp';return $('matchMessage').textContent='Kunne ikke avbryte: '+error.message}await setPlayersUnavailable();window.opener?.postMessage({type:'dartarena-match-ended',id:m.id},location.origin);closeMatchTab()};
$('closeMatchBtn').onclick=()=>{if(m?.status==='playing'&&!confirm('Kampen pågår fortsatt. Du kan åpne den igjen fra lobbyen. Lukk kampfanen?'))return;window.close();if(!window.closed)location.href='./'};
function cleanup(){leaving=true;clearInterval(publicationTimer);publicationTimer=null;stream?.getTracks?.().forEach(t=>t.stop());stream=null;publisherSfu?.close();subscriberSfu?.close();publisherSfu=subscriberSfu=null;if(channel)db.removeChannel(channel).catch?.(()=>{});channel=null}
window.addEventListener('beforeunload',cleanup);
