const SUPABASE_URL='https://jqpxlbhwvskhjbqrbidk.supabase.co',SUPABASE_KEY='sb_publishable_aqx1Q36C3cznImJ5KMDk3w_I1uUTHQK',db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY),$=id=>document.getElementById(id);
const matchId=new URLSearchParams(location.search).get('id');
let profile,m,other,names={},channel,stream=null,pc=null,remoteStream=null;
let localReady=false,remoteReady=false,leaving=false,generation=1,lastSignal='START';
let pendingCandidates=[],readyTimer=null,reconnectTimer=null,statsTimer=null,answerWatchTimer=null,offerTimeout=null;
let recoveryInFlight=false,lastRecoveryAt=0,lastOfferAt=0;
let lastVideoBytes=-1,lastVideoFrames=-1,lastVideoTime=-1,videoStalls=0,candidatePath='?';
const ICE={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302','stun:stun2.l.google.com:19302']}],iceCandidatePoolSize:10,bundlePolicy:'max-bundle'};
const isOfferer=()=>profile?.id===m?.player1_id;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function debug(extra=''){const e=$('webrtcDebug');if(!e)return;e.textContent=`VIDEO DEBUG • RT:${channel?'ON':'OFF'} | Local:${localReady?'YES':'NO'} | Remote:${remoteReady?'YES':'NO'} | Role:${isOfferer()?'OFFER':'ANSWER'} | Peer:${pc?.connectionState||'none'} | ICE:${pc?.iceConnectionState||'none'} | Path:${candidatePath} | Signal:${pc?.signalingState||'none'} | Gen:${generation} | Recovery:${recoveryInFlight?'YES':'NO'} | Last:${lastSignal}${extra?' | '+extra:''}`}
(async()=>{const{data:{session}}=await db.auth.getSession();if(!session||!matchId)return location.replace('./');({data:profile}=await db.from('profiles').select('*').eq('id',session.user.id).single());const{data,error}=await db.from('matches').select('*').eq('id',matchId).single();m=data;if(error||!m||![m.player1_id,m.player2_id].includes(profile.id))return location.replace('./');other=profile.id===m.player1_id?m.player2_id:m.player1_id;const{data:p}=await db.from('profiles').select('id,username').in('id',[m.player1_id,m.player2_id]);names=Object.fromEntries((p||[]).map(x=>[x.id,x.username]));$('matchName1').textContent=names[m.player1_id]||'Spiller 1';$('matchName2').textContent=names[m.player2_id]||'Spiller 2';$('localVideoName').textContent=names[profile.id]||'Spiller';$('remoteVideoName').textContent=names[other]||'Spiller';$('matchTitle').textContent=`${names[m.player1_id]||'Spiller 1'} vs ${names[m.player2_id]||'Spiller 2'}`;$('matchFormat').textContent=`${m.game} • BEST OF ${m.legs}`;render();setupChannel()})();
function focusScore(){const i=$('matchScoreInput');if(!i||i.disabled)return;requestAnimationFrame(()=>{i.focus({preventScroll:true});i.select()})}
function render(){if(!m)return;$('matchScore1').textContent=m.player1_score;$('matchScore2').textContent=m.player2_score;$('matchLegs1').textContent=`${m.player1_legs} legs`;$('matchLegs2').textContent=`${m.player2_legs} legs`;const mine=m.turn_player_id===profile.id&&m.status==='playing';$('matchP1').classList.toggle('active',m.turn_player_id===m.player1_id&&m.status==='playing');$('matchP2').classList.toggle('active',m.turn_player_id===m.player2_id&&m.status==='playing');$('videoGrid')?.classList.toggle('opponent-throwing',m.status==='playing'&&!mine);$('turnText').textContent=m.status==='cancelled'?'Kampen er avbrutt.':m.status==='finished'?`${names[m.winner_id]||'Vinner'} vant kampen.`:mine?'Din tur':`${names[m.turn_player_id]||'Motstanderen'} kaster`;$('matchStatus').textContent=m.status==='playing'?'Pågår':m.status==='finished'?'Ferdig':'Avbrutt';$('matchScoreBtn').disabled=!mine;$('matchScoreInput').disabled=!mine;$('cancelMatchBtn').classList.toggle('hidden',m.status!=='playing');if(mine)focusScore()}
async function score(v){const n=Number(v);if(!m||m.status!=='playing'||m.turn_player_id!==profile.id||!Number.isInteger(n)||n<0||n>180)return;const p1=profile.id===m.player1_id,sk=p1?'player1_score':'player2_score',lk=p1?'player1_legs':'player2_legs',left=m[sk]-n,patch={updated_at:new Date().toISOString()};if(left<0||left===1){patch.turn_player_id=other;$('matchMessage').textContent='Bust.'}else if(left===0){const legs=m[lk]+1,needed=Math.floor(m.legs/2)+1;patch[lk]=legs;if(legs>=needed){patch[sk]=0;patch.status='finished';patch.winner_id=profile.id;patch.finished_at=new Date().toISOString()}else{patch.player1_score=m.game;patch.player2_score=m.game;patch.turn_player_id=other}$('matchMessage').textContent='Leg vunnet!'}else{patch[sk]=left;patch.turn_player_id=other;$('matchMessage').textContent=''}const{data,error}=await db.from('matches').update(patch).eq('id',m.id).select().single();if(error){$('matchMessage').textContent=error.message;return focusScore()}m=data;$('matchScoreInput').value='';render();if(m.status==='finished')await setPlayersUnavailable()}
$('matchScoreBtn').onclick=()=>score($('matchScoreInput').value);$('matchScoreInput').onkeydown=e=>{if(e.key==='Enter')score(e.target.value)};
function setupChannel(){channel=db.channel('match-'+m.id,{config:{broadcast:{ack:true}}}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'matches',filter:`id=eq.${m.id}`},async p=>{m=p.new;render();if(m.status!=='playing')await setPlayersUnavailable()}).on('broadcast',{event:'ready'},async({payload})=>{if(payload.from!==other)return;remoteReady=true;const rg=Number(payload.generation)||1;if(!pc&&rg>generation)generation=rg;lastSignal=`READY received g${rg}`;debug();if(isOfferer())await connectIfReady();else armAnswerWatch()}).on('broadcast',{event:'signal'},async({payload})=>{if(payload.from!==other)return;remoteReady=true;await handleSignal(payload)}).on('broadcast',{event:'reconnect-request'},async({payload})=>{if(payload.from!==other||!isOfferer()||leaving)return;const now=Date.now();lastSignal=`RECOVERY requested ${payload.reason||''}`;debug();if(recoveryInFlight||now-lastRecoveryAt<6000)return;await rebuildAsOfferer(payload.reason||'remote-request')}).subscribe(async s=>{lastSignal=`RT ${s}`;debug();if(s==='SUBSCRIBED'){await startCamera();startReadyHeartbeat()}})}
function startReadyHeartbeat(){clearInterval(readyTimer);readyTimer=setInterval(()=>{if(!leaving&&localReady)send('ready',{generation});if(!isOfferer()&&localReady&&remoteReady&&!pc&&!recoveryInFlight)armAnswerWatch()},4000)}
function armAnswerWatch(){if(isOfferer()||leaving||!localReady||!remoteReady||pc||answerWatchTimer||recoveryInFlight)return;lastSignal='ANSWER waiting for offer';debug();answerWatchTimer=setTimeout(async()=>{answerWatchTimer=null;if(leaving||isOfferer()||pc||!localReady||!remoteReady||recoveryInFlight)return;await requestRecovery('answer-no-peer')},3500)}
function cameraErrorText(e){if(e?.name==='NotAllowedError')return'Kamera/mikrofon er blokkert i nettleseren.';if(e?.name==='NotFoundError')return'Fant ikke kamera eller mikrofon.';if(e?.name==='NotReadableError')return'Kameraet kan være i bruk av et annet program.';return`Kamera kunne ikke startes${e?.name?' ('+e.name+')':''}.`}
async function startCamera(){if(stream?.active){localReady=true;await send('ready',{generation});if(isOfferer())await connectIfReady();else armAnswerWatch();return}try{stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const v=$('localVideo');v.srcObject=stream;v.muted=true;await v.play().catch(()=>{});$('localPlaceholder').classList.add('hidden');$('cameraBtn').textContent='Stopp kamera';localReady=true;lastSignal='CAMERA ready';debug();await send('ready',{generation});if(isOfferer())await connectIfReady();else armAnswerWatch()}catch(e){localReady=false;$('localPlaceholder').classList.remove('hidden');$('localPlaceholder').textContent=cameraErrorText(e);$('matchMessage').textContent=cameraErrorText(e);lastSignal=`CAMERA ${e?.name||'error'}`;debug()}}
function showRemotePlaceholder(text){const p=$('remotePlaceholder');if(p){p.textContent=text;p.classList.remove('hidden')}}function hideRemotePlaceholder(){$('remotePlaceholder')?.classList.add('hidden')}
function clearPeer(){clearTimeout(reconnectTimer);reconnectTimer=null;clearTimeout(answerWatchTimer);answerWatchTimer=null;clearTimeout(offerTimeout);offerTimeout=null;clearInterval(statsTimer);statsTimer=null;pendingCandidates=[];lastVideoBytes=-1;lastVideoFrames=-1;lastVideoTime=-1;videoStalls=0;candidatePath='?';if(pc){pc.ontrack=pc.onicecandidate=pc.onconnectionstatechange=pc.oniceconnectionstatechange=null;try{pc.close()}catch{}}pc=null;remoteStream=null;const v=$('remoteVideo');if(v){v.pause?.();v.srcObject=null}showRemotePlaceholder('Kobler til video…')}
function attachRemoteTrack(e,myGen,p){if(p!==pc||myGen!==generation)return;if(!remoteStream)remoteStream=new MediaStream();const t=e.track;if(!remoteStream.getTracks().some(x=>x.id===t.id))remoteStream.addTrack(t);const v=$('remoteVideo');v.srcObject=remoteStream;lastSignal=`TRACK ${t.kind}`;if(t.kind==='video'){const play=async()=>{if(p!==pc||myGen!==generation)return;try{v.muted=true;await v.play();hideRemotePlaceholder()}catch{showRemotePlaceholder('Klikk i siden for å starte video')}};t.onunmute=play;t.onmute=()=>scheduleRecovery(5000,'remote-track-muted');t.onended=()=>requestRecovery('remote-track-ended');v.onloadedmetadata=play;v.oncanplay=play;play()}debug()}
function createPeer(){if(pc||!stream?.active)return pc;clearTimeout(answerWatchTimer);answerWatchTimer=null;const myGen=generation,p=new RTCPeerConnection(ICE);pc=p;remoteStream=new MediaStream();$('remoteVideo').srcObject=remoteStream;for(const t of stream.getTracks())p.addTrack(t,stream);p.ontrack=e=>attachRemoteTrack(e,myGen,p);p.onicecandidate=e=>{if(p!==pc||myGen!==generation||!e.candidate)return;send('signal',{candidate:e.candidate.toJSON?e.candidate.toJSON():e.candidate,generation:myGen});lastSignal=`ICE sent ${e.candidate.type||''}`;debug()};p.oniceconnectionstatechange=()=>{if(p!==pc)return;lastSignal=`ICE ${p.iceConnectionState}`;debug();if(p.iceConnectionState==='disconnected')scheduleRecovery(5000,'ice-disconnected');else if(p.iceConnectionState==='failed')requestRecovery('ice-failed')};p.onconnectionstatechange=()=>{if(p!==pc)return;lastSignal=`PEER ${p.connectionState}`;debug();if(p.connectionState==='connected'){recoveryInFlight=false;clearTimeout(reconnectTimer);reconnectTimer=null;clearTimeout(offerTimeout);offerTimeout=null;startStatsWatch(p,myGen)}else if(p.connectionState==='disconnected')scheduleRecovery(5000,'peer-disconnected');else if(p.connectionState==='failed')requestRecovery('peer-failed')};return p}
async function connectIfReady(){if(leaving||!isOfferer()||!localReady||!remoteReady||!stream?.active)return;if(pc){if(pc.connectionState==='connected'||pc.signalingState==='have-local-offer')return;if(pc.signalingState!=='stable')return}const p=createPeer();if(!p||p.signalingState!=='stable'||p.localDescription)return;try{lastOfferAt=Date.now();const offer=await p.createOffer();if(p!==pc)return;await p.setLocalDescription(offer);lastSignal=`OFFER sent g${generation}`;debug();await send('signal',{description:p.localDescription.toJSON?p.localDescription.toJSON():p.localDescription,generation});clearTimeout(offerTimeout);offerTimeout=setTimeout(()=>{if(p===pc&&p.signalingState==='have-local-offer'&&p.connectionState!=='connected'){lastSignal='OFFER timeout';debug();requestRecovery('offer-timeout')}},10000)}catch(e){lastSignal=`OFFER ${e?.name||'error'}`;debug();scheduleRecovery(3000,'offer-error')}}
async function handleSignal(s){if(leaving||!localReady||!stream?.active)return;const sg=Number(s.generation)||1;if(sg<generation)return;
if(s.description?.type==='offer'){if(isOfferer())return;clearTimeout(answerWatchTimer);answerWatchTimer=null;recoveryInFlight=true;if(sg!==generation||pc){clearPeer();generation=sg}else generation=sg;const p=createPeer();if(!p)return;try{await p.setRemoteDescription(s.description);await flushCandidates(p);const answer=await p.createAnswer();if(p!==pc)return;await p.setLocalDescription(answer);lastSignal=`ANSWER sent g${generation}`;debug();await send('signal',{description:p.localDescription.toJSON?p.localDescription.toJSON():p.localDescription,generation})}catch(e){lastSignal=`ANSWER ${e?.name||'error'}`;debug();recoveryInFlight=false;scheduleRecovery(3000,'answer-error')}return}
if(s.candidate){if(sg>generation){if(pc)clearPeer();generation=sg}if(!pc){pendingCandidates.push({candidate:s.candidate,generation:sg});lastSignal=`ICE queued g${sg}`;debug();return}try{if(pc.remoteDescription)await pc.addIceCandidate(s.candidate);else pendingCandidates.push({candidate:s.candidate,generation:sg});lastSignal=pc.remoteDescription?'ICE added':'ICE queued';debug()}catch(e){lastSignal=`ICE ${e?.name||'error'}`;debug()}return}
if(s.description?.type==='answer'){if(!isOfferer()||!pc||sg!==generation||pc.signalingState!=='have-local-offer')return;try{await pc.setRemoteDescription(s.description);await flushCandidates(pc);clearTimeout(offerTimeout);offerTimeout=null;lastSignal=`ANSWER set g${generation}`;debug()}catch(e){lastSignal=`ANSWER SET ${e?.name||'error'}`;debug();scheduleRecovery(3000,'answer-set-error')}}}
async function flushCandidates(p){const keep=[];for(const item of pendingCandidates){if(p!==pc)break;if(item.generation!==generation){if(item.generation>generation)keep.push(item);continue}if(!p.remoteDescription){keep.push(item);continue}try{await p.addIceCandidate(item.candidate)}catch{}}pendingCandidates=keep}
function updateCandidatePath(stats){let pair=null;stats.forEach(r=>{if(r.type==='transport'&&r.selectedCandidatePairId)pair=stats.get(r.selectedCandidatePairId);if(!pair&&r.type==='candidate-pair'&&r.state==='succeeded'&&r.nominated)pair=r});if(!pair)return;const local=stats.get(pair.localCandidateId),remote=stats.get(pair.remoteCandidateId);candidatePath=`${local?.candidateType||'?'}>${remote?.candidateType||'?'}`}
function startStatsWatch(p,myGen){clearInterval(statsTimer);lastVideoBytes=-1;lastVideoFrames=-1;lastVideoTime=-1;videoStalls=0;statsTimer=setInterval(async()=>{if(leaving||p!==pc||myGen!==generation||p.connectionState!=='connected')return;try{const stats=await p.getStats();updateCandidatePath(stats);let bytes=0,frames=0,found=false;stats.forEach(r=>{if(r.type==='inbound-rtp'&&r.kind==='video'&&!r.isRemote){found=true;bytes+=Number(r.bytesReceived||0);frames+=Number(r.framesDecoded||0)}});if(!found)return;const v=$('remoteVideo'),videoTime=Number(v?.currentTime||0);const bytesMoving=lastVideoBytes<0||bytes>lastVideoBytes,framesMoving=lastVideoFrames<0||frames>lastVideoFrames,timeMoving=lastVideoTime<0||videoTime>lastVideoTime+.01;if(bytesMoving&&framesMoving&&timeMoving){videoStalls=0;hideRemotePlaceholder()}else if(lastVideoBytes>=0){videoStalls++;lastSignal=`VIDEO stall ${videoStalls}/8 b:${bytesMoving?'Y':'N'} f:${framesMoving?'Y':'N'} t:${timeMoving?'Y':'N'}`;debug();if(videoStalls>=8){showRemotePlaceholder('Gjenoppretter video…');requestRecovery('video-frozen')}}lastVideoBytes=bytes;lastVideoFrames=frames;lastVideoTime=videoTime;if(!videoStalls){lastSignal=`VIDEO ${Math.round(bytes/1024)}KB/${frames}f`;debug()}}catch(e){lastSignal=`STATS ${e?.name||'error'}`;debug()}},1000)}
function scheduleRecovery(ms,reason){if(leaving||reconnectTimer||recoveryInFlight)return;reconnectTimer=setTimeout(()=>{reconnectTimer=null;requestRecovery(reason)},ms)}
async function requestRecovery(reason){if(leaving)return;const now=Date.now();if(recoveryInFlight||now-lastRecoveryAt<6000)return;lastRecoveryAt=now;recoveryInFlight=true;lastSignal=`RECOVERY ${reason}`;debug();showRemotePlaceholder('Gjenoppretter video…');if(isOfferer()){await rebuildAsOfferer(reason);return}await send('reconnect-request',{reason,generation});setTimeout(()=>{if(leaving||pc?.connectionState==='connected')return;recoveryInFlight=false;armAnswerWatch()},10000)}
async function rebuildAsOfferer(reason){if(leaving||!isOfferer())return;lastRecoveryAt=Date.now();recoveryInFlight=true;generation+=1;lastSignal=`REBUILD g${generation} ${reason}`;debug();clearPeer();await sleep(350);await send('ready',{generation});await connectIfReady();setTimeout(()=>{if(leaving||pc?.connectionState==='connected')return;recoveryInFlight=false;debug()},10000)}
async function send(event,payload={}){if(!channel)return'no-channel';try{const r=await channel.send({type:'broadcast',event,payload:{...payload,from:profile.id}});return r}catch(e){lastSignal=`SEND ${event} failed`;debug();return'error'}}
$('cameraBtn').onclick=async()=>{if(!stream)return startCamera();localReady=false;stream.getTracks().forEach(t=>t.stop());stream=null;recoveryInFlight=false;clearPeer();$('localVideo').srcObject=null;$('localPlaceholder').classList.remove('hidden');showRemotePlaceholder('Venter på motstanderens kamera…');$('cameraBtn').textContent='Start kamera';lastSignal='CAMERA stopped';debug()};
async function setPlayersUnavailable(){if(m)await db.from('profiles').update({status:'unavailable'}).in('id',[m.player1_id,m.player2_id])}
function closeMatchTab(){cleanup();window.close();setTimeout(()=>{if(!window.closed){document.body.innerHTML='<main class="shell"><section class="card" style="max-width:520px;margin:10vh auto;text-align:center"><h2>Kampen er avbrutt</h2><p class="muted">Denne kampfanen kan nå lukkes.</p><button class="primary" onclick="window.close()">Lukk fane</button></section></main>'}},150)}
$('cancelMatchBtn').onclick=async()=>{if(!m||m.status!=='playing'||!confirm('Vil du avbryte kampen?'))return;const{error}=await db.from('matches').update({status:'cancelled',finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',m.id);if(error)return $('matchMessage').textContent='Kunne ikke avbryte: '+error.message;await setPlayersUnavailable();window.opener?.postMessage({type:'dartarena-match-ended',id:m.id},location.origin);closeMatchTab()};
$('closeMatchBtn').onclick=()=>{if(m?.status==='playing'&&!confirm('Kampen pågår fortsatt. Du kan åpne den igjen fra lobbyen. Lukk kampfanen?'))return;window.close();if(!window.closed)location.href='./'};
function cleanup(){leaving=true;localReady=false;clearInterval(readyTimer);clearInterval(statsTimer);clearTimeout(reconnectTimer);clearTimeout(answerWatchTimer);clearTimeout(offerTimeout);stream?.getTracks().forEach(t=>t.stop());stream=null;clearPeer();if(channel)db.removeChannel(channel)}window.addEventListener('beforeunload',cleanup);