const SUPABASE_URL='https://jqpxlbhwvskhjbqrbidk.supabase.co',SUPABASE_KEY='sb_publishable_aqx1Q36C3cznImJ5KMDk3w_I1uUTHQK',db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY),$=id=>document.getElementById(id);
const matchId=new URLSearchParams(location.search).get('id');
let profile,m,other,names={},channel,stream,pc,remoteStream=null;
let localReady=false,remoteReady=false,leaving=false,pendingCandidates=[],generation=1,lastSignal='START',reconnectTimer=null;
const ICE={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302','stun:stun2.l.google.com:19302']}],iceCandidatePoolSize:10,bundlePolicy:'max-bundle'};
const isOfferer=()=>profile?.id===m?.player1_id;
function debug(extra=''){const e=$('webrtcDebug');if(!e)return;e.textContent=`VIDEO DEBUG • Local:${localReady?'YES':'NO'} | Remote:${remoteReady?'YES':'NO'} | Role:${isOfferer()?'OFFER':'ANSWER'} | Peer:${pc?.connectionState||'none'} | ICE:${pc?.iceConnectionState||'none'} | Signal:${pc?.signalingState||'none'} | Gen:${generation} | Last:${lastSignal}${extra?' | '+extra:''}`}

(async()=>{const{data:{session}}=await db.auth.getSession();if(!session||!matchId)return location.replace('./');({data:profile}=await db.from('profiles').select('*').eq('id',session.user.id).single());const{data,error}=await db.from('matches').select('*').eq('id',matchId).single();m=data;if(error||!m||![m.player1_id,m.player2_id].includes(profile.id))return location.replace('./');other=profile.id===m.player1_id?m.player2_id:m.player1_id;const{data:p}=await db.from('profiles').select('id,username').in('id',[m.player1_id,m.player2_id]);names=Object.fromEntries((p||[]).map(x=>[x.id,x.username]));$('matchName1').textContent=names[m.player1_id]||'Spiller 1';$('matchName2').textContent=names[m.player2_id]||'Spiller 2';$('localVideoName').textContent=names[profile.id]||'Spiller';$('remoteVideoName').textContent=names[other]||'Spiller';$('matchTitle').textContent=`${names[m.player1_id]||'Spiller 1'} vs ${names[m.player2_id]||'Spiller 2'}`;$('matchFormat').textContent=`${m.game} • BEST OF ${m.legs}`;render();setupChannel()})();

function focusScore(){const i=$('matchScoreInput');if(!i||i.disabled)return;requestAnimationFrame(()=>{i.focus({preventScroll:true});i.select()})}
function render(){if(!m)return;$('matchScore1').textContent=m.player1_score;$('matchScore2').textContent=m.player2_score;$('matchLegs1').textContent=`${m.player1_legs} legs`;$('matchLegs2').textContent=`${m.player2_legs} legs`;const mine=m.turn_player_id===profile.id&&m.status==='playing';$('matchP1').classList.toggle('active',m.turn_player_id===m.player1_id&&m.status==='playing');$('matchP2').classList.toggle('active',m.turn_player_id===m.player2_id&&m.status==='playing');$('videoGrid')?.classList.toggle('opponent-throwing',m.status==='playing'&&!mine);$('turnText').textContent=m.status==='cancelled'?'Kampen er avbrutt.':m.status==='finished'?`${names[m.winner_id]||'Vinner'} vant kampen.`:mine?'Din tur':`${names[m.turn_player_id]||'Motstanderen'} kaster`;$('matchStatus').textContent=m.status==='playing'?'Pågår':m.status==='finished'?'Ferdig':'Avbrutt';$('matchScoreBtn').disabled=!mine;$('matchScoreInput').disabled=!mine;$('cancelMatchBtn').classList.toggle('hidden',m.status!=='playing');if(mine)focusScore()}

async function score(v){const n=Number(v);if(!m||m.status!=='playing'||m.turn_player_id!==profile.id||!Number.isInteger(n)||n<0||n>180)return;const p1=profile.id===m.player1_id,sk=p1?'player1_score':'player2_score',lk=p1?'player1_legs':'player2_legs',left=m[sk]-n,patch={updated_at:new Date().toISOString()};if(left<0||left===1){patch.turn_player_id=other;$('matchMessage').textContent='Bust.'}else if(left===0){const legs=m[lk]+1,needed=Math.floor(m.legs/2)+1;patch[lk]=legs;if(legs>=needed){patch[sk]=0;patch.status='finished';patch.winner_id=profile.id;patch.finished_at=new Date().toISOString()}else{patch.player1_score=m.game;patch.player2_score=m.game;patch.turn_player_id=other}$('matchMessage').textContent='Leg vunnet!'}else{patch[sk]=left;patch.turn_player_id=other;$('matchMessage').textContent=''}const{data,error}=await db.from('matches').update(patch).eq('id',m.id).select().single();if(error){$('matchMessage').textContent=error.message;return focusScore()}m=data;$('matchScoreInput').value='';render();if(m.status==='finished')await setPlayersUnavailable()}
$('matchScoreBtn').onclick=()=>score($('matchScoreInput').value);$('matchScoreInput').onkeydown=e=>{if(e.key==='Enter')score(e.target.value)};

function setupChannel(){channel=db.channel('match-'+m.id)
.on('postgres_changes',{event:'UPDATE',schema:'public',table:'matches',filter:`id=eq.${m.id}`},async p=>{m=p.new;render();if(m.status!=='playing')await setPlayersUnavailable()})
.on('broadcast',{event:'ready'},async({payload})=>{if(payload.from!==other)return;remoteReady=true;lastSignal='READY received';debug();await connectIfReady()})
.on('broadcast',{event:'signal'},async({payload})=>{if(payload.from!==other)return;remoteReady=true;await handleSignal(payload)})
.on('broadcast',{event:'reset'},async({payload})=>{if(payload.from!==other||(payload.generation||0)<=generation)return;generation=payload.generation;lastSignal='RESET received';await rebuild(false)})
.subscribe(async s=>{lastSignal=`RT ${s}`;debug();if(s==='SUBSCRIBED')await startCamera()})}

function cameraErrorText(e){if(e?.name==='NotAllowedError')return'Kamera/mikrofon er blokkert i nettleseren.';if(e?.name==='NotFoundError')return'Fant ikke kamera eller mikrofon.';if(e?.name==='NotReadableError')return'Kameraet kan være i bruk av et annet program.';return`Kamera kunne ikke startes${e?.name?' ('+e.name+')':''}.`}
async function startCamera(){if(stream){await send('ready',{generation});return connectIfReady()}try{stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});$('localVideo').srcObject=stream;await $('localVideo').play().catch(()=>{});$('localPlaceholder').classList.add('hidden');$('cameraBtn').textContent='Stopp kamera';localReady=true;lastSignal='CAMERA ready';debug();await send('ready',{generation});setTimeout(()=>localReady&&send('ready',{generation}),1000);setTimeout(()=>localReady&&send('ready',{generation}),3000);await connectIfReady()}catch(e){localReady=false;$('localPlaceholder').classList.remove('hidden');$('localPlaceholder').textContent=cameraErrorText(e);$('matchMessage').textContent=cameraErrorText(e);lastSignal=`CAMERA ${e?.name||'error'}`;debug()}}

function destroyPeer(){clearTimeout(reconnectTimer);reconnectTimer=null;pendingCandidates=[];if(pc){pc.ontrack=pc.onicecandidate=pc.onconnectionstatechange=pc.oniceconnectionstatechange=null;try{pc.close()}catch{}}pc=null;remoteStream=null;const v=$('remoteVideo');if(v)v.srcObject=null}
function attachRemote(e){if(!remoteStream)remoteStream=new MediaStream();const t=e.track;remoteStream.getTracks().filter(x=>x.kind===t.kind&&x.id!==t.id).forEach(x=>remoteStream.removeTrack(x));if(!remoteStream.getTracks().some(x=>x.id===t.id))remoteStream.addTrack(t);const v=$('remoteVideo');if(v.srcObject!==remoteStream)v.srcObject=remoteStream;remoteReady=true;lastSignal=`TRACK ${t.kind}`;if(t.kind==='video'){v.muted=true;v.playsInline=true;const wake=()=>v.play().then(()=>{$('remotePlaceholder').classList.add('hidden')}).catch(()=>{});v.onloadedmetadata=wake;v.oncanplay=wake;t.onunmute=wake;wake()}debug()}
function createPeer(){if(pc)return pc;const myGen=generation,p=new RTCPeerConnection(ICE);pc=p;remoteStream=new MediaStream();$('remoteVideo').srcObject=remoteStream;stream.getTracks().forEach(t=>p.addTrack(t,stream));p.ontrack=e=>{if(p===pc&&myGen===generation)attachRemote(e)};p.onicecandidate=e=>{if(p!==pc||myGen!==generation||!e.candidate)return;lastSignal='ICE sent';send('signal',{candidate:e.candidate,generation:myGen});debug()};p.oniceconnectionstatechange=()=>{if(p===pc){lastSignal=`ICE ${p.iceConnectionState}`;debug()}};p.onconnectionstatechange=()=>{if(p!==pc)return;lastSignal=`PEER ${p.connectionState}`;debug();if(p.connectionState==='connected'){clearTimeout(reconnectTimer);reconnectTimer=null}else if(p.connectionState==='disconnected')scheduleReconnect(7000,'disconnected');else if(p.connectionState==='failed')scheduleReconnect(500,'failed')};return p}
async function connectIfReady(){if(!localReady||!remoteReady||!stream)return;const p=createPeer();if(!isOfferer()||p.signalingState!=='stable'||p.localDescription)return;try{const offer=await p.createOffer();await p.setLocalDescription(offer);lastSignal='OFFER sent';debug();await send('signal',{description:p.localDescription,generation})}catch(e){lastSignal=`OFFER ${e?.name||'error'}`;debug()}}
async function handleSignal(s){if(!localReady||!stream)return;const sg=Number(s.generation)||generation;if(sg<generation)return;if(sg>generation){generation=sg;destroyPeer()}const p=createPeer();try{if(s.description?.type==='offer'){if(isOfferer()||p.signalingState!=='stable')return;await p.setRemoteDescription(s.description);await flushCandidates(p);const answer=await p.createAnswer();await p.setLocalDescription(answer);lastSignal='ANSWER sent';debug();await send('signal',{description:p.localDescription,generation})}else if(s.description?.type==='answer'){if(!isOfferer()||p.signalingState!=='have-local-offer')return;await p.setRemoteDescription(s.description);await flushCandidates(p);lastSignal='ANSWER set';debug()}else if(s.candidate){if(p.remoteDescription)await p.addIceCandidate(s.candidate);else pendingCandidates.push(s.candidate);lastSignal=p.remoteDescription?'ICE added':'ICE queued';debug()}}catch(e){lastSignal=`SIGNAL ${e?.name||'error'}`;debug();scheduleReconnect(2000,'signal-error')}}
async function flushCandidates(p){while(pendingCandidates.length&&p===pc){try{await p.addIceCandidate(pendingCandidates.shift())}catch{}}}
function scheduleReconnect(ms,reason){if(leaving||reconnectTimer)return;reconnectTimer=setTimeout(()=>{reconnectTimer=null;if(!pc||['failed','disconnected'].includes(pc.connectionState))beginReset(reason)},ms)}
async function beginReset(reason){if(leaving)return;generation=Date.now();lastSignal=`RESET ${reason}`;debug();await send('reset',{generation,reason});await rebuild(true)}
async function rebuild(){destroyPeer();$('remotePlaceholder').classList.remove('hidden');$('remotePlaceholder').textContent='Kobler til video…';await new Promise(r=>setTimeout(r,300));if(localReady&&remoteReady)await connectIfReady()}
async function send(event,payload={}){if(channel)await channel.send({type:'broadcast',event,payload:{...payload,from:profile.id}})}

$('cameraBtn').onclick=async()=>{if(!stream)return startCamera();localReady=false;stream.getTracks().forEach(t=>t.stop());stream=null;destroyPeer();$('localVideo').srcObject=null;$('remoteVideo').srcObject=null;$('localPlaceholder').classList.remove('hidden');$('remotePlaceholder').classList.remove('hidden');$('remotePlaceholder').textContent='Venter på motstanderens kamera…';$('cameraBtn').textContent='Start kamera';lastSignal='CAMERA stopped';debug()};
async function setPlayersUnavailable(){if(m)await db.from('profiles').update({status:'unavailable'}).in('id',[m.player1_id,m.player2_id])}
$('cancelMatchBtn').onclick=async()=>{if(!m||m.status!=='playing'||!confirm('Vil du avbryte kampen?'))return;const{error}=await db.from('matches').update({status:'cancelled',finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',m.id);if(error)return $('matchMessage').textContent='Kunne ikke avbryte: '+error.message;await setPlayersUnavailable();window.opener?.postMessage({type:'dartarena-match-ended',id:m.id},location.origin)};
$('closeMatchBtn').onclick=()=>{if(m?.status==='playing'&&!confirm('Kampen pågår fortsatt. Du kan åpne den igjen fra lobbyen. Lukk kampfanen?'))return;window.close();if(!window.closed)location.href='./'};
function cleanup(){leaving=true;localReady=false;stream?.getTracks().forEach(t=>t.stop());stream=null;destroyPeer()}
window.addEventListener('beforeunload',cleanup);