const SUPABASE_URL='https://jqpxlbhwvskhjbqrbidk.supabase.co',SUPABASE_KEY='sb_publishable_aqx1Q36C3cznImJ5KMDk3w_I1uUTHQK',db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY),$=id=>document.getElementById(id);
const challengeId=new URLSearchParams(location.search).get('id');
let profile,c,other,names={},channel,stream,pc,pendingProposal=null,leaving=false,localReady=false,remoteReady=false,matchMode='legs';
let pendingCandidates=[],reconnectTimer=null,remoteStream=null,helloTimer=null,offerBusy=false;
const ICE={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302','stun:stun2.l.google.com:19302']}]};
const isOfferer=()=>profile?.id===c?.challenger_id;
const setStatus=t=>{$('cameraStatus').textContent=t};
const selectedGame=()=>$('roomGame')?.value||'501';
const variantForGame=g=>g==='cricket'?'cricket':g==='half_it'?'half_it':g==='sixty_one'?'sixty_one':'x01';
const isSpecialGame=()=>['cricket','half_it','sixty_one'].includes(selectedGame());
const pageForVariant=v=>v==='cricket'?'cricket.html':v==='half_it'?'half-it.html':v==='sixty_one'?'61-match.html':'match.html';
const gameLabel=g=>g==='cricket'?'Cricket':g==='half_it'?'Half-It':g==='sixty_one'?'61':String(g);
function setMatchMode(mode){const special=isSpecialGame();matchMode=special?'legs':mode==='sets'?'sets':'legs';$('legsModeBtn').classList.toggle('active',matchMode==='legs');$('setsModeBtn').classList.toggle('active',matchMode==='sets');$('setsField').classList.toggle('hidden',matchMode!=='sets')}
function syncGameMode(){const g=selectedGame(),special=isSpecialGame(),half=g==='half_it',sixty=g==='sixty_one';$('setsModeBtn').disabled=special;$('legsModeBtn').disabled=half;$('legsField').classList.toggle('hidden',half);$('sixtyOneTimeField').classList.toggle('hidden',!sixty);if(half)$('roomLegs').value='1';if(special)setMatchMode('legs')}
$('legsModeBtn').onclick=()=>setMatchMode('legs');$('setsModeBtn').onclick=()=>setMatchMode('sets');$('roomGame').onchange=syncGameMode;setMatchMode('legs');syncGameMode();
(async()=>{const{data:{session}}=await db.auth.getSession();if(!session||!challengeId)return location.replace('./');({data:profile}=await db.from('profiles').select('*').eq('id',session.user.id).single());const{data,error}=await db.from('challenges').select('*').eq('id',challengeId).single();c=data;if(error||!c||![c.challenger_id,c.challenged_id].includes(profile.id)||c.status!=='room')return location.replace('./');other=profile.id===c.challenger_id?c.challenged_id:c.challenger_id;const{data:p}=await db.from('profiles').select('id,username').in('id',[profile.id,other]);names=Object.fromEntries((p||[]).map(x=>[x.id,x.username]));$('roomTitle').textContent=`${names[profile.id]||'Spiller'} vs ${names[other]||'Spiller'}`;$('localVideoName').textContent=names[profile.id]||'Spiller';$('remoteVideoName').textContent=names[other]||'Spiller';setupChannel()})();
function setupChannel(){channel=db.channel('room-'+challengeId).on('broadcast',{event:'ready'},async({payload})=>{if(payload.from!==other)return;remoteReady=true;await connectIfReady()}).on('broadcast',{event:'signal'},async({payload})=>{if(payload.from!==other)return;remoteReady=true;await handleSignal(payload)}).on('broadcast',{event:'proposal'},({payload})=>{if(payload.from!==profile.id)showProposal(payload)}).on('broadcast',{event:'proposal-rejected'},({payload})=>{if(payload.from!==profile.id)$('roomMessage').textContent='Motstanderen avslo kampforslaget.'}).on('broadcast',{event:'room-cancelled'},({payload})=>{if(payload.from!==profile.id)closeRoomTab('Motstanderen avsluttet venterommet.')}).on('broadcast',{event:'match-start'},({payload})=>{if(!payload.matchId)return;location.href=`${pageForVariant(payload.gameVariant)}?id=${encodeURIComponent(payload.matchId)}`}).subscribe(async s=>{if(s==='SUBSCRIBED'){await startCamera();startHandshake()}})}
function startHandshake(){clearInterval(helloTimer);helloTimer=setInterval(async()=>{if(!localReady||leaving)return;await send('ready');if(remoteReady&&(!pc||['failed','closed'].includes(pc.connectionState)))await restartPeer()},1500)}
function cameraErrorText(e){if(e?.name==='NotAllowedError')return'Kamera/mikrofon er blokkert i nettleseren.';if(e?.name==='NotFoundError')return'Fant ikke kamera eller mikrofon.';if(e?.name==='NotReadableError')return'Kameraet kan være i bruk av et annet program.';return'Kamera kunne ikke startes.'}
async function startCamera(){const retry=$('retryCameraBtn');retry.classList.add('hidden');if(stream){await send('ready');return connectIfReady()}setStatus('Starter kamera…');try{stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const v=$('localVideo');v.srcObject=stream;await v.play().catch(()=>{});$('localPlaceholder').classList.add('hidden');localReady=true;setStatus('Kamera klart – venter på motstander…');await send('ready');await connectIfReady()}catch(e){localReady=false;$('localPlaceholder').classList.remove('hidden');$('localPlaceholder').textContent='Kamera ikke startet';setStatus(cameraErrorText(e));retry.classList.remove('hidden')}}$('retryCameraBtn').onclick=startCamera;
function destroyPeer(){clearTimeout(reconnectTimer);reconnectTimer=null;pendingCandidates=[];offerBusy=false;if(pc){pc.ontrack=pc.onicecandidate=pc.onconnectionstatechange=pc.oniceconnectionstatechange=null;try{pc.close()}catch{}}pc=null;remoteStream=null;const v=$('remoteVideo');if(v){v.pause();v.srcObject=null}$('remotePlaceholder').classList.remove('hidden');$('remoteAudioBtn').classList.add('hidden')}
function createPeer(){if(pc)return pc;const p=new RTCPeerConnection(ICE);pc=p;remoteStream=new MediaStream();for(const track of stream.getTracks())p.addTrack(track,stream);p.onicecandidate=e=>{if(p===pc&&e.candidate)send('signal',{candidate:e.candidate})};p.ontrack=e=>{if(p!==pc)return;const tracks=e.streams?.[0]?.getTracks()||[e.track];for(const track of tracks){if(!remoteStream.getTracks().some(t=>t.id===track.id))remoteStream.addTrack(track);track.onunmute=()=>showRemote();track.onended=()=>scheduleReconnect(1000)}showRemote()};p.onconnectionstatechange=()=>{if(p!==pc)return;const s=p.connectionState;if(s==='connected'){clearTimeout(reconnectTimer);setStatus(`Tilkoblet ${names[other]||'motstander'}`);showRemote()}else if(s==='failed')scheduleReconnect(500);else if(s==='disconnected')scheduleReconnect(8000)};p.oniceconnectionstatechange=()=>{if(p!==pc)return;if(p.iceConnectionState==='failed')scheduleReconnect(500)};return p}
async function showRemote(){const v=$('remoteVideo');if(!remoteStream||!remoteStream.getTracks().length)return;v.srcObject=remoteStream;v.muted=true;v.playsInline=true;try{await v.play()}catch{}const live=remoteStream.getVideoTracks().some(t=>t.readyState==='live');if(live){$('remotePlaceholder').classList.add('hidden');$('remoteAudioBtn').classList.remove('hidden')}}
function waitForIce(p,timeout=3000){if(p.iceGatheringState==='complete')return Promise.resolve();return new Promise(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;p.removeEventListener('icegatheringstatechange',check);resolve()};const check=()=>{if(p.iceGatheringState==='complete')finish()};p.addEventListener('icegatheringstatechange',check);setTimeout(finish,timeout)})}
async function connectIfReady(){if(!localReady||!remoteReady||!stream||!isOfferer()||offerBusy)return;const p=createPeer();if(p.connectionState==='connected'||p.signalingState!=='stable')return;offerBusy=true;try{const offer=await p.createOffer({offerToReceiveAudio:true,offerToReceiveVideo:true});await p.setLocalDescription(offer);await waitForIce(p);await send('signal',{description:p.localDescription})}catch{scheduleReconnect(1200)}finally{offerBusy=false}}
async function handleSignal(s){if(!localReady||!stream)return;const p=createPeer();try{if(s.description?.type==='offer'){if(isOfferer())return;if(p.signalingState!=='stable'){await restartPeer(false);return handleSignal(s)}await p.setRemoteDescription(s.description);await flushCandidates(p);const answer=await p.createAnswer();await p.setLocalDescription(answer);await waitForIce(p);await send('signal',{description:p.localDescription})}else if(s.description?.type==='answer'){if(!isOfferer()||p.signalingState!=='have-local-offer')return;await p.setRemoteDescription(s.description);await flushCandidates(p)}else if(s.candidate){if(p.remoteDescription)await p.addIceCandidate(s.candidate).catch(()=>{});else pendingCandidates.push(s.candidate)}}catch{scheduleReconnect(1200)}}
async function flushCandidates(p){while(pendingCandidates.length&&p===pc){await p.addIceCandidate(pendingCandidates.shift()).catch(()=>{})}}
function scheduleReconnect(ms){if(leaving||reconnectTimer)return;reconnectTimer=setTimeout(async()=>{reconnectTimer=null;if(!pc||pc.connectionState!=='connected')await restartPeer()},ms)}async function restartPeer(start=true){destroyPeer();setStatus('Kobler video til på nytt…');await new Promise(r=>setTimeout(r,300));if(start&&localReady&&remoteReady)await connectIfReady()}
$('remoteAudioBtn').onclick=async()=>{const v=$('remoteVideo'),b=$('remoteAudioBtn');v.muted=!v.muted;b.textContent=v.muted?'Slå på lyd':'Slå av lyd';try{await v.play()}catch{v.muted=true;b.textContent='Slå på lyd'}};async function send(event,payload={}){if(channel)await channel.send({type:'broadcast',event,payload:{...payload,from:profile.id}})}
$('proposalBtn').onclick=async()=>{const rawGame=selectedGame(),variant=variantForGame(rawGame),half=variant==='half_it',sixty=variant==='sixty_one',special=variant!=='x01',game=special?rawGame:Number(rawGame),mode=special?'legs':matchMode,legs=half?1:Number($('roomLegs').value),sets=special?1:(mode==='sets'?Number($('roomSets').value):1),durationMinutes=sixty?Number($('room61Time').value):null,choice=$('roomStarter').value;if(!half&&(legs<1||legs%2===0||sets<1||sets%2===0)){$('roomMessage').textContent='Best of må være et oddetall.';return}if(sixty&&![10,20,30,45,60].includes(durationMinutes)){$('roomMessage').textContent='Velg gyldig tid per leg.';return}const starter=choice==='me'?profile.id:choice==='opponent'?other:'random',payload={game,gameVariant:variant,legs,sets,mode,starter,durationMinutes};await send('proposal',payload);const label=gameLabel(game);$('roomMessage').textContent=half?`Forslag sendt: ${label} • 12 runder`:sixty?`Forslag sendt: 61 • Best of ${legs} legs • ${durationMinutes} min/leg`:mode==='sets'?`Forslag sendt: ${label} • Best of ${sets} sets • Best of ${legs} legs`:`Forslag sendt: ${label} • Best of ${legs} legs`};
function showProposal(p){const variant=p.gameVariant==='sixty_one'||p.game==='sixty_one'?'sixty_one':p.gameVariant==='half_it'||p.game==='half_it'?'half_it':p.gameVariant==='cricket'||p.game==='cricket'?'cricket':'x01',special=variant!=='x01',half=variant==='half_it',sixty=variant==='sixty_one',durationMinutes=sixty&&[10,20,30,45,60].includes(Number(p.durationMinutes))?Number(p.durationMinutes):10;pendingProposal={...p,gameVariant:variant,mode:special?'legs':p.mode||'legs',sets:special?1:Number(p.sets)||1,legs:half?1:Number(p.legs)||1,durationMinutes};const who=p.starter==='random'?'Tilfeldig':p.starter===profile.id?'Du starter':`${names[other]} starter`;const label=sixty?'61':half?'Half-It':variant==='cricket'?'Cricket':p.game;const format=half?`${label} • 12 runder`:sixty?`${label} • Best of ${pendingProposal.legs} legs • ${durationMinutes} min/leg`:pendingProposal.mode==='sets'?`${label} • Best of ${pendingProposal.sets} sets • Best of ${pendingProposal.legs} legs`:`${label} • Best of ${pendingProposal.legs} legs`;$('proposalTitle').textContent=format;$('proposalText').textContent=`${who}. Godta for å starte kampen.`;$('proposalActions').classList.remove('hidden')}
$('rejectProposalBtn').onclick=async()=>{pendingProposal=null;$('proposalActions').classList.add('hidden');$('proposalTitle').textContent='Ingen forslag ennå';$('proposalText').textContent='Dere kan avtale et nytt oppsett.';await send('proposal-rejected')};
$('acceptProposalBtn').onclick=async()=>{if(!pendingProposal)return;const b=$('acceptProposalBtn');b.disabled=true;b.textContent='Starter…';let first=pendingProposal.starter;if(first==='random')first=Math.random()<.5?profile.id:other;const variant=pendingProposal.gameVariant||'x01',special=variant!=='x01',sixty=variant==='sixty_one',numericGame=special?501:Number(pendingProposal.game),initialScore=sixty?61:special?0:numericGame,row={player1_id:c.challenger_id,player2_id:c.challenged_id,game:numericGame,game_variant:variant,legs:variant==='half_it'?1:pendingProposal.legs,status:'playing',turn_player_id:first,player1_score:initialScore,player2_score:initialScore,match_mode:special?'legs':pendingProposal.mode,best_of_sets:special?1:(pendingProposal.mode==='sets'?pendingProposal.sets:1),player1_sets:0,player2_sets:0,match_starter_id:first,current_set:1,current_leg:1,game_config:sixty?{duration_seconds:pendingProposal.durationMinutes*60}:{}};const{data:m,error}=await db.from('matches').insert(row).select().single();if(error){b.disabled=false;b.textContent='Godta og start kamp';$('roomMessage').textContent=error.message;return}await db.from('challenges').update({status:'accepted'}).eq('id',challengeId);await db.from('profiles').update({status:'in_game'}).in('id',[c.challenger_id,c.challenged_id]);await send('match-start',{matchId:m.id,gameVariant:variant});location.href=`${pageForVariant(variant)}?id=${encodeURIComponent(m.id)}`};
function cleanup(){clearInterval(helloTimer);helloTimer=null;localReady=false;stream?.getTracks().forEach(t=>t.stop());stream=null;destroyPeer()}
function closeRoomTab(message=''){cleanup();let hasOpener=false;try{hasOpener=!!window.opener&&!window.opener.closed;if(hasOpener)window.opener.postMessage({type:'dartarena-room-cancelled',id:challengeId,message},location.origin)}catch{}if(hasOpener){window.close();setTimeout(()=>{if(!window.closed)location.replace('./')},150);return}location.replace('./')}
$('leaveRoomBtn').onclick=async()=>{if(leaving)return;leaving=true;const b=$('leaveRoomBtn');b.disabled=true;b.textContent='Avslutter…';await send('room-cancelled').catch(()=>{});const{error}=await db.from('challenges').update({status:'cancelled'}).eq('id',challengeId).eq('status','room');if(error){b.disabled=false;b.textContent='Avbryt venterom';leaving=false;$('roomMessage').textContent='Kunne ikke avslutte venterommet: '+error.message;return}closeRoomTab()};window.addEventListener('beforeunload',cleanup);