(()=>{
  if(!window.supabase)return;
  const db=window.supabase.createClient('https://jqpxlbhwvskhjbqrbidk.supabase.co','sb_publishable_aqx1Q36C3cznImJ5KMDk3w_I1uUTHQK');
  const $=id=>document.getElementById(id),matchId=new URLSearchParams(location.search).get('id');
  let match=null,names={},timer=null,channel=null,leaving=false,clients=new Map(),publications=new Map();
  const isX01=m=>!['jdc','cricket','half_it','sixty_one'].includes(m?.game_variant||'x01');
  function gameLabel(m){if(m.game_variant==='jdc')return'JDC Challenge';if(m.game_variant==='cricket')return'Cricket';if(m.game_variant==='half_it')return'Half-It';if(m.game_variant==='sixty_one')return'61';return String(m.game||501)}
  function formatLabel(m){if(m.game_variant==='jdc')return'57 piler hver';if(m.game_variant==='half_it')return'12 runder';return`Best of ${Number(m.legs||1)}`}
  function render(){if(!match)return;const p1=names[match.player1_id]||'Spiller 1',p2=names[match.player2_id]||'Spiller 2';$('spectateTitle').textContent=`${p1} vs ${p2}`;$('spectateName1').textContent=p1;$('spectateName2').textContent=p2;$('spectatePlayer1').textContent=p1;$('spectatePlayer2').textContent=p2;$('spectateGame').textContent=gameLabel(match);$('spectateFormat').textContent=(match.is_warmup?'Oppvarming • ':'')+formatLabel(match);$('spectateStatus').textContent=match.status==='playing'?(match.is_warmup?'Pågår • Oppvarming':'Pågår'):match.status==='finished'?'Ferdig':'Avbrutt';if(match.game_variant==='jdc'){$('spectateResult1').textContent=String(Number(match.player1_score||0));$('spectateResult2').textContent=String(Number(match.player2_score||0));$('spectateSub1').textContent='poeng';$('spectateSub2').textContent='poeng'}else{$('spectateResult1').textContent=String(Number(match.player1_legs||0));$('spectateResult2').textContent=String(Number(match.player2_legs||0));$('spectateSub1').textContent=`${Number(match.player1_score||0)} gjenstår`;$('spectateSub2').textContent=`${Number(match.player2_score||0)} gjenstår`}if(!isX01(match)){[$('spectatePlaceholder1'),$('spectatePlaceholder2')].forEach(el=>{if(el){el.textContent='Live video er foreløpig ikke koblet til denne spilltypen.';el.classList.remove('hidden')}})}}
  async function refresh(){if(!matchId)return;const {data:m,error}=await db.from('matches').select('*').eq('id',matchId).maybeSingle();if(error||!m){$('spectateTitle').textContent='Kampen finnes ikke';return}match=m;if(!Object.keys(names).length){const{data:p}=await db.from('profiles').select('id,username').in('id',[m.player1_id,m.player2_id]);names=Object.fromEntries((p||[]).map(x=>[x.id,x.username]))}render()}
  async function subscribePlayer(playerId,pub){if(!isX01(match)||!playerId||!pub?.sessionId||!window.DartArenaSFU||!window.DARTARENA_SFU)return;const index=playerId===match.player1_id?1:playerId===match.player2_id?2:0;if(!index)return;const old=publications.get(playerId);if(old===pub.sessionId)return;publications.set(playerId,pub.sessionId);try{clients.get(playerId)?.close()}catch{}const client=new window.DartArenaSFU(window.DARTARENA_SFU.workerUrl);clients.set(playerId,client);const video=$(`spectateVideo${index}`),placeholder=$(`spectatePlaceholder${index}`);video.srcObject=new MediaStream();await client.subscribe(pub,async event=>{if(leaving)return;let rs=video.srcObject;if(!(rs instanceof MediaStream)){rs=new MediaStream();video.srcObject=rs}const tracks=event.streams?.[0]?.getTracks?.()||[event.track];tracks.forEach(track=>{if(track&&!rs.getTracks().some(t=>t.id===track.id))rs.addTrack(track)});video.muted=true;await video.play().catch(()=>{});if(rs.getVideoTracks().some(t=>t.readyState==='live'))placeholder?.classList.add('hidden')})}catch(e){console.warn('Spectator subscribe failed',e);publications.delete(playerId)}}
  async function setupVideo(){if(!isX01(match))return;channel=db.channel(`match-spectator-media-${matchId}`).on('broadcast',{event:'spectator-publication'},({payload})=>{if(payload?.from&&payload?.publication)subscribePlayer(payload.from,payload.publication)}).subscribe(async status=>{if(status==='SUBSCRIBED')await channel.send({type:'broadcast',event:'spectator-request',payload:{from:'spectator'}}).catch(()=>{})})}
  async function boot(){const{data:{session}}=await db.auth.getSession();if(!session)return location.replace('./');await refresh();await setupVideo();timer=setInterval(refresh,1500)}
  function cleanup(){leaving=true;clearInterval(timer);clients.forEach(c=>{try{c.close()}catch{}});clients.clear();if(channel)db.removeChannel(channel).catch(()=>{});channel=null}
  window.addEventListener('pagehide',cleanup,{once:true});boot().catch(e=>{console.error('Spectate failed',e);$('spectateTitle').textContent='Kunne ikke laste kampen'})
})();