(()=>{
const $=id=>document.getElementById(id),wait=setInterval(()=>{if(!window.supabase||!$('matchView'))return;clearInterval(wait);boot()},100);
async function boot(){
 const matchId=new URLSearchParams(location.search).get('id');if(!matchId)return;
 const db=window.supabase.createClient('https://jqpxlbhwvskhjbqrbidk.supabase.co','sb_publishable_aqx1Q36C3cznImJ5KMDk3w_I1uUTHQK');
 const {data:{session}}=await db.auth.getSession();if(!session)return;const me=session.user.id;
 let {data:match}=await db.from('matches').select('*').eq('id',matchId).single();if(!match)return;
 let throws=[];
 const style=document.createElement('style');style.textContent='.stats-card{margin-top:10px}.stats-title{display:flex;justify-content:space-between;align-items:end;gap:12px;margin-bottom:10px}.stats-title h3{margin:0;font-size:16px}.stats-grid{display:grid;grid-template-columns:150px 1fr 1fr;border:1px solid rgba(255,255,255,.08);border-radius:12px;overflow:hidden}.stats-grid>*{padding:8px 10px;border-bottom:1px solid rgba(255,255,255,.06)}.stats-grid>*:nth-last-child(-n+3){border-bottom:0}.stats-grid .label{color:#88a1a5;font-size:12px}.stats-grid .val{text-align:center;font-weight:900}.stats-grid .head{color:#23e2d1;font-size:12px;font-weight:900}.final-stats-overlay{position:fixed;inset:0;z-index:10000;background:rgba(2,7,8,.88);display:grid;place-items:center;padding:20px;overflow:auto}.final-stats-card{width:min(760px,96vw);background:#0c171a;border:1px solid #203438;border-radius:18px;padding:24px;box-shadow:0 25px 80px #000b}.final-stats-card h2{text-align:center;margin:0 0 4px}.final-result{text-align:center;color:#23e2d1;font-weight:950;font-size:24px;margin-bottom:18px}.final-close{margin-top:18px;width:100%}@media(max-width:600px){.stats-grid{grid-template-columns:100px 1fr 1fr}.stats-grid>*{padding:7px 5px;font-size:12px}}';document.head.appendChild(style);
 const host=document.querySelector('.match-grid');const live=document.createElement('section');live.className='card stats-card';live.innerHTML='<div class="stats-title"><h3>Live-statistikk</h3><small>HELE KAMPEN</small></div><div id="liveStats"></div>';host?.insertAdjacentElement('afterend',live);
 function names(){return[$('matchName1')?.textContent||'Spiller 1',$('matchName2')?.textContent||'Spiller 2']}
 function playerStats(pid){const t=throws.filter(x=>x.player_id===pid);const total=t.reduce((s,x)=>s+Number(x.score||0),0),darts=t.reduce((s,x)=>s+Number(x.is_checkout?x.darts_used:3),0);return{avg:darts?total/darts*3:0,c100:t.filter(x=>x.score>=100&&x.score<=139).length,c140:t.filter(x=>x.score>=140&&x.score<=169).length,c170:t.filter(x=>x.score>=170&&x.score<=179).length,c180:t.filter(x=>x.score===180).length,fast:fastest(pid)}}
 function fastest(pid){const wins=throws.filter(x=>x.player_id===pid&&x.is_checkout);let best=null;for(const w of wins){const leg=throws.filter(x=>x.player_id===pid&&x.set_no===w.set_no&&x.leg_no===w.leg_no);const darts=leg.reduce((s,x)=>s+Number(x.is_checkout?x.darts_used:3),0);if(best===null||darts<best)best=darts}return best}
 function grid(){const a=playerStats(match.player1_id),b=playerStats(match.player2_id),[n1,n2]=names(),rows=[['3-dart avg',a.avg.toFixed(2),b.avg.toFixed(2)],['Raskeste leg',a.fast?`${a.fast} piler`:'–',b.fast?`${b.fast} piler`:'–'],['100+',a.c100,b.c100],['140+',a.c140,b.c140],['170+',a.c170,b.c170],['180',a.c180,b.c180]];return'<div class="stats-grid"><div></div><div class="val head">'+esc(n1)+'</div><div class="val head">'+esc(n2)+'</div>'+rows.map(r=>`<div class="label">${r[0]}</div><div class="val">${r[1]}</div><div class="val">${r[2]}</div>`).join('')+'</div>'}
 function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function draw(){if($('liveStats'))$('liveStats').innerHTML=grid();if(match.status==='finished')showFinal()}
 function showFinal(){if($('finalStatsOverlay'))return;const [n1,n2]=names(),sets=match.match_mode==='sets',result=sets?`${match.player1_sets||0} – ${match.player2_sets||0}`:`${match.player1_legs||0} – ${match.player2_legs||0}`;const ov=document.createElement('div');ov.id='finalStatsOverlay';ov.className='final-stats-overlay';ov.innerHTML=`<div class="final-stats-card"><small>KAMP FERDIG</small><h2>${esc(n1)} vs ${esc(n2)}</h2><div class="final-result">${result}</div>${grid()}<button class="outline final-close" type="button">Lukk statistikk</button></div>`;document.body.appendChild(ov);ov.querySelector('.final-close').onclick=()=>ov.remove()}
 async function loadThrows(){const {data,error}=await db.from('match_throws').select('*').eq('match_id',matchId).order('created_at',{ascending:true});if(!error)throws=data||[];draw()}
 db.channel('stats-'+matchId).on('postgres_changes',{event:'*',schema:'public',table:'match_throws',filter:`match_id=eq.${matchId}`},()=>loadThrows()).on('postgres_changes',{event:'UPDATE',schema:'public',table:'matches',filter:`id=eq.${matchId}`},p=>{match=p.new;draw()}).subscribe();
 await loadThrows();
}
})();