-- JDC Challenge: solo is training; only completed online JDC matches feed Top 10/tier.

alter table public.jdc_challenge_results
  add column if not exists result_source text not null default 'solo',
  add column if not exists match_id uuid references public.matches(id) on delete set null;

alter table public.jdc_challenge_results drop constraint if exists jdc_challenge_results_result_source_check;
alter table public.jdc_challenge_results add constraint jdc_challenge_results_result_source_check
  check (result_source in ('solo','online'));

create unique index if not exists jdc_challenge_results_online_match_player_uq
  on public.jdc_challenge_results(match_id,user_id)
  where result_source='online' and match_id is not null;

drop view if exists public.jdc_challenge_best;
create view public.jdc_challenge_best with (security_invoker=true) as
select distinct on (r.user_id)
  r.user_id,p.username,r.score as best_score,r.phase1_score,r.doubles_score,r.phase3_score,
  r.doubles_hit,r.shanghai_count,r.badge,r.created_at as achieved_at,r.id as result_id
from public.jdc_challenge_results r
join public.profiles p on p.id=r.user_id
where r.result_source='online'
order by r.user_id,r.score desc,r.created_at asc;
revoke all on public.jdc_challenge_best from anon;
grant select on public.jdc_challenge_best to authenticated;

alter table public.matches drop constraint if exists matches_game_variant_check;
alter table public.matches add constraint matches_game_variant_check
  check (game_variant in ('x01','cricket','half_it','sixty_one','jdc'));
alter table public.challenge_match_proposals drop constraint if exists challenge_match_proposals_game_variant_check;
alter table public.challenge_match_proposals add constraint challenge_match_proposals_game_variant_check
  check (game_variant in ('x01','cricket','half_it','sixty_one','jdc'));

create table if not exists public.jdc_match_turns(
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  turn_no smallint not null check(turn_no between 1 and 33),
  hits jsonb not null,
  points integer not null check(points between 0 and 280),
  shanghai_bonus boolean not null default false,
  created_at timestamptz not null default now(),
  unique(match_id,player_id,turn_no)
);
alter table public.jdc_match_turns enable row level security;
drop policy if exists "JDC match participants can read turns" on public.jdc_match_turns;
create policy "JDC match participants can read turns" on public.jdc_match_turns
for select to authenticated using(exists(
  select 1 from public.matches m where m.id=jdc_match_turns.match_id
  and (auth.uid() in (m.player1_id,m.player2_id) or public.is_admin())
));
revoke all on public.jdc_match_turns from anon;
revoke insert,update,delete,truncate,references,trigger on public.jdc_match_turns from authenticated;
grant select on public.jdc_match_turns to authenticated;
revoke all on sequence public.jdc_match_turns_id_seq from anon,authenticated;

create or replace function public.record_jdc_online_result(p_match_id uuid,p_user_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_score integer;v_phase1 integer;v_doubles integer;v_phase3 integer;v_doubles_hit integer;v_shanghai integer;
  v_badge text;v_hits text[];
begin
  select case when m.player1_id=p_user_id then m.player1_score else m.player2_score end into v_score
  from public.matches m where m.id=p_match_id and p_user_id in(m.player1_id,m.player2_id);
  if v_score is null then raise exception 'Player is not part of JDC match'; end if;
  select coalesce(sum(points) filter(where turn_no between 1 and 6),0),
         coalesce(sum(points) filter(where turn_no between 7 and 27),0),
         coalesce(sum(points) filter(where turn_no between 28 and 33),0),
         coalesce(count(*) filter(where turn_no between 7 and 27 and hits->>0='H'),0),
         coalesce(count(*) filter(where shanghai_bonus),0)
  into v_phase1,v_doubles,v_phase3,v_doubles_hit,v_shanghai
  from public.jdc_match_turns where match_id=p_match_id and player_id=p_user_id;
  select array_agg(e.value order by t.turn_no,e.ord) into v_hits
  from public.jdc_match_turns t
  cross join lateral jsonb_array_elements_text(t.hits) with ordinality e(value,ord)
  where t.match_id=p_match_id and t.player_id=p_user_id;
  if coalesce(array_length(v_hits,1),0)<>57 then raise exception 'Incomplete JDC result'; end if;
  v_badge:=case when v_score>=1250 then 'gold' when v_score>=850 then 'black' when v_score>=700 then 'red'
    when v_score>=600 then 'blue' when v_score>=450 then 'green' when v_score>=300 then 'yellow'
    when v_score>=150 then 'purple' else 'white' end;
  insert into public.jdc_challenge_results(user_id,score,phase1_score,doubles_score,phase3_score,doubles_hit,shanghai_count,badge,hits,result_source,match_id)
  values(p_user_id,v_score,v_phase1,v_doubles,v_phase3,v_doubles_hit,v_shanghai,v_badge,to_jsonb(v_hits),'online',p_match_id)
  on conflict(match_id,user_id) where result_source='online' and match_id is not null do nothing;
end;$$;
revoke all on function public.record_jdc_online_result(uuid,uuid) from public,anon,authenticated;

create or replace function public.submit_jdc_match_turn(p_match_id uuid,p_hits text[])
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_uid uuid:=auth.uid();m public.matches%rowtype;v_other uuid;v_turn integer;v_other_count integer;v_expected integer;
  v_target integer;v_code text;v_points integer:=0;v_s boolean:=false;v_d boolean:=false;v_t boolean:=false;
  v_bonus boolean:=false;v_next uuid;v_winner uuid;i integer;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  select * into m from public.matches where id=p_match_id for update;
  if not found or m.game_variant<>'jdc' then raise exception 'JDC match not found'; end if;
  if v_uid not in(m.player1_id,m.player2_id) then raise exception 'Not a participant'; end if;
  if m.status<>'playing' then raise exception 'Match is not active'; end if;
  if m.turn_player_id<>v_uid then raise exception 'It is not your turn'; end if;
  v_other:=case when v_uid=m.player1_id then m.player2_id else m.player1_id end;
  select count(*)+1 into v_turn from public.jdc_match_turns where match_id=p_match_id and player_id=v_uid;
  if v_turn>33 then raise exception 'JDC challenge already complete'; end if;
  v_expected:=case when v_turn between 7 and 27 then 1 else 3 end;
  if coalesce(array_length(p_hits,1),0)<>v_expected then raise exception 'Wrong number of darts for this target'; end if;
  if v_turn between 1 and 6 or v_turn between 28 and 33 then
    v_target:=case when v_turn<=6 then 9+v_turn else v_turn-13 end;
    for i in 1..3 loop
      v_code:=upper(coalesce(p_hits[i],''));
      if v_code='M' then null; elsif v_code='S' then v_points:=v_points+v_target;v_s:=true;
      elsif v_code='D' then v_points:=v_points+2*v_target;v_d:=true;
      elsif v_code='T' then v_points:=v_points+3*v_target;v_t:=true;
      else raise exception 'Invalid Shanghai hit';end if;
    end loop;
    if v_s and v_d and v_t then v_points:=v_points+100;v_bonus:=true;end if;
  else
    v_code:=upper(coalesce(p_hits[1],''));
    if v_code='M' then null;elsif v_code='H' then v_points:=case when v_turn=27 then 100 else 50 end;
    else raise exception 'Invalid doubles hit';end if;
  end if;
  insert into public.jdc_match_turns(match_id,player_id,turn_no,hits,points,shanghai_bonus)
    values(p_match_id,v_uid,v_turn,to_jsonb(p_hits),v_points,v_bonus);
  update public.matches set
    player1_score=case when v_uid=player1_id then player1_score+v_points else player1_score end,
    player2_score=case when v_uid=player2_id then player2_score+v_points else player2_score end,updated_at=now()
  where id=p_match_id returning * into m;
  select count(*) into v_other_count from public.jdc_match_turns where match_id=p_match_id and player_id=v_other;
  if v_turn=33 and v_other_count=33 then
    v_winner:=case when m.player1_score>m.player2_score then m.player1_id when m.player2_score>m.player1_score then m.player2_id else null end;
    update public.matches set status='finished',winner_id=v_winner,finished_at=now(),turn_player_id=null,
      player1_legs=case when v_winner=m.player1_id then 1 else 0 end,
      player2_legs=case when v_winner=m.player2_id then 1 else 0 end,updated_at=now()
    where id=p_match_id returning * into m;
    perform public.record_jdc_online_result(p_match_id,m.player1_id);
    perform public.record_jdc_online_result(p_match_id,m.player2_id);
    update public.profiles set status='available',last_seen=now() where id in(m.player1_id,m.player2_id);
  else
    v_next:=case when v_other_count<v_turn then v_other else coalesce(m.match_starter_id,m.player1_id) end;
    update public.matches set turn_player_id=v_next,updated_at=now() where id=p_match_id returning * into m;
  end if;
  return jsonb_build_object('match_id',m.id,'status',m.status,'turn_player_id',m.turn_player_id,
    'player1_score',m.player1_score,'player2_score',m.player2_score,'winner_id',m.winner_id,'turn_no',v_turn,'points',v_points,'shanghai_bonus',v_bonus);
end;$$;
revoke all on function public.submit_jdc_match_turn(uuid,text[]) from public,anon;
grant execute on function public.submit_jdc_match_turn(uuid,text[]) to authenticated;

create or replace function public.undo_jdc_match_turn(p_match_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_uid uuid:=auth.uid();m public.matches%rowtype;r public.jdc_match_turns%rowtype;v_other uuid;v_other_count integer;
begin
  if v_uid is null then raise exception 'Authentication required';end if;
  select * into m from public.matches where id=p_match_id for update;
  if not found or m.game_variant<>'jdc' then raise exception 'JDC match not found';end if;
  if v_uid not in(m.player1_id,m.player2_id) then raise exception 'Not a participant';end if;
  if m.status<>'playing' then raise exception 'Match is not active';end if;
  v_other:=case when v_uid=m.player1_id then m.player2_id else m.player1_id end;
  select * into r from public.jdc_match_turns where match_id=p_match_id and player_id=v_uid order by turn_no desc limit 1 for update;
  if not found then raise exception 'Nothing to undo';end if;
  select count(*) into v_other_count from public.jdc_match_turns where match_id=p_match_id and player_id=v_other;
  if v_other_count>=r.turn_no then raise exception 'Motstanderen har allerede registrert dette målet';end if;
  delete from public.jdc_match_turns where id=r.id;
  update public.matches set
    player1_score=case when v_uid=player1_id then greatest(0,player1_score-r.points) else player1_score end,
    player2_score=case when v_uid=player2_id then greatest(0,player2_score-r.points) else player2_score end,
    turn_player_id=v_uid,updated_at=now()
  where id=p_match_id returning * into m;
  return jsonb_build_object('status',m.status,'turn_player_id',m.turn_player_id,'player1_score',m.player1_score,'player2_score',m.player2_score);
end;$$;
revoke all on function public.undo_jdc_match_turn(uuid) from public,anon;
grant execute on function public.undo_jdc_match_turn(uuid) to authenticated;

-- The deployed migration also extends create_match_from_challenge() and propose_challenge_match()
-- to accept game_variant='jdc', force one 57-dart challenge per match, initialize scores at 0,
-- and set game_config={"ranked":true}. Keep those generic match RPCs in sync when applying manually.
