-- DartArena: kastlogg for aktivt leg og senere kampstatistikk
create table if not exists public.match_throws (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  set_no integer not null default 1 check (set_no >= 1),
  leg_no integer not null default 1 check (leg_no >= 1),
  visit_no integer not null check (visit_no >= 1),
  score integer not null check (score >= 0 and score <= 180),
  darts_used integer not null default 3 check (darts_used between 1 and 3),
  is_checkout boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(match_id, player_id, set_no, leg_no, visit_no)
);

create index if not exists match_throws_match_leg_idx
  on public.match_throws(match_id, set_no, leg_no, created_at);

alter table public.match_throws enable row level security;

drop policy if exists "match players can read throws" on public.match_throws;
create policy "match players can read throws"
on public.match_throws for select
to authenticated
using (
  exists (
    select 1 from public.matches m
    where m.id = match_id
      and auth.uid() in (m.player1_id, m.player2_id)
  )
);

drop policy if exists "players can insert own throws" on public.match_throws;
create policy "players can insert own throws"
on public.match_throws for insert
to authenticated
with check (
  auth.uid() = player_id
  and exists (
    select 1 from public.matches m
    where m.id = match_id
      and auth.uid() in (m.player1_id, m.player2_id)
      and m.status = 'playing'
  )
);

drop policy if exists "players can update own throws" on public.match_throws;
create policy "players can update own throws"
on public.match_throws for update
to authenticated
using (auth.uid() = player_id)
with check (auth.uid() = player_id);

-- Realtime for live kastliste.
do $$ begin
  alter publication supabase_realtime add table public.match_throws;
exception
  when duplicate_object then null;
end $$;