-- DartArena Cricket support
-- Adds a game variant without changing the existing X01 game column.

begin;

alter table public.matches
  add column if not exists game_variant text not null default 'x01';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'matches_game_variant_check'
      and conrelid = 'public.matches'::regclass
  ) then
    alter table public.matches
      add constraint matches_game_variant_check
      check (game_variant in ('x01','cricket'));
  end if;
end $$;

create table if not exists public.cricket_match_state (
  match_id uuid primary key references public.matches(id) on delete cascade,
  player1_marks jsonb not null default '{"20":0,"19":0,"18":0,"17":0,"16":0,"15":0,"B":0}'::jsonb,
  player2_marks jsonb not null default '{"20":0,"19":0,"18":0,"17":0,"16":0,"15":0,"B":0}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.cricket_visits (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  leg_no integer not null check (leg_no >= 1),
  visit_no integer not null check (visit_no >= 1),
  darts jsonb not null,
  points_scored integer not null default 0 check (points_scored >= 0),
  created_at timestamptz not null default now()
);

create index if not exists cricket_visits_match_leg_idx
  on public.cricket_visits(match_id, leg_no, id);

alter table public.cricket_match_state enable row level security;
alter table public.cricket_visits enable row level security;

revoke all on public.cricket_match_state from anon;
revoke all on public.cricket_visits from anon;
revoke insert, update, delete on public.cricket_match_state from authenticated;
revoke insert, update, delete on public.cricket_visits from authenticated;
grant select on public.cricket_match_state to authenticated;
grant select on public.cricket_visits to authenticated;

drop policy if exists "players read cricket state" on public.cricket_match_state;
create policy "players read cricket state"
on public.cricket_match_state
for select
to authenticated
using (
  exists (
    select 1 from public.matches m
    where m.id = cricket_match_state.match_id
      and (select auth.uid()) in (m.player1_id, m.player2_id)
  )
);

drop policy if exists "players read cricket visits" on public.cricket_visits;
create policy "players read cricket visits"
on public.cricket_visits
for select
to authenticated
using (
  exists (
    select 1 from public.matches m
    where m.id = cricket_visits.match_id
      and (select auth.uid()) in (m.player1_id, m.player2_id)
  )
);

create or replace function public.init_cricket_match_state()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.game_variant = 'cricket' then
    insert into public.cricket_match_state(match_id)
    values (new.id)
    on conflict (match_id) do nothing;
  end if;
  return new;
end;
$$;

revoke execute on function public.init_cricket_match_state() from public, anon, authenticated;

drop trigger if exists trg_init_cricket_match_state on public.matches;
create trigger trg_init_cricket_match_state
after insert on public.matches
for each row execute function public.init_cricket_match_state();

create or replace function public.submit_cricket_visit(
  p_match_id uuid,
  p_darts jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_match public.matches%rowtype;
  v_state public.cricket_match_state%rowtype;
  v_dart jsonb;
  v_target text;
  v_key text;
  v_mult integer;
  v_value integer;
  v_own_marks jsonb;
  v_opp_marks jsonb;
  v_current integer;
  v_opp integer;
  v_close integer;
  v_extra integer;
  v_points integer;
  v_opp_points integer;
  v_points_scored integer := 0;
  v_is_p1 boolean;
  v_all_closed boolean;
  v_leg_won boolean := false;
  v_new_legs integer;
  v_needed integer;
  v_other uuid;
  v_next_starter uuid;
  v_visit_no integer;
  v_empty_marks jsonb := '{"20":0,"19":0,"18":0,"17":0,"16":0,"15":0,"B":0}'::jsonb;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_darts is null or jsonb_typeof(p_darts) <> 'array' then raise exception 'Darts must be an array'; end if;
  if jsonb_array_length(p_darts) < 1 or jsonb_array_length(p_darts) > 3 then raise exception 'A cricket visit must contain 1 to 3 darts'; end if;

  select * into v_match from public.matches where id = p_match_id for update;
  if not found then raise exception 'Match not found'; end if;
  if v_match.game_variant <> 'cricket' then raise exception 'This is not a cricket match'; end if;
  if v_match.status <> 'playing' then raise exception 'Match is not active'; end if;
  if auth.uid() not in (v_match.player1_id, v_match.player2_id) then raise exception 'You are not a player in this match'; end if;
  if v_match.turn_player_id is distinct from auth.uid() then raise exception 'It is not your turn'; end if;

  select * into v_state from public.cricket_match_state where match_id = p_match_id for update;
  if not found then
    insert into public.cricket_match_state(match_id) values (p_match_id) returning * into v_state;
  end if;

  v_is_p1 := auth.uid() = v_match.player1_id;
  v_other := case when v_is_p1 then v_match.player2_id else v_match.player1_id end;
  v_own_marks := case when v_is_p1 then v_state.player1_marks else v_state.player2_marks end;
  v_opp_marks := case when v_is_p1 then v_state.player2_marks else v_state.player1_marks end;
  v_points := case when v_is_p1 then v_match.player1_score else v_match.player2_score end;
  v_opp_points := case when v_is_p1 then v_match.player2_score else v_match.player1_score end;

  for v_dart in select value from jsonb_array_elements(p_darts)
  loop
    v_target := upper(coalesce(v_dart->>'target',''));
    v_mult := coalesce((v_dart->>'mult')::integer, 0);
    if v_target = 'MISS' then
      if v_mult <> 0 then raise exception 'MISS must have multiplier 0'; end if;
      continue;
    end if;
    if v_target in ('20','19','18','17','16','15') then
      if v_mult not between 1 and 3 then raise exception 'Number targets must use multiplier 1, 2 or 3'; end if;
      v_key := v_target; v_value := v_target::integer;
    elsif v_target in ('B','BULL') then
      if v_mult not between 1 and 2 then raise exception 'Bull must use multiplier 1 or 2'; end if;
      v_key := 'B'; v_value := 25;
    else
      raise exception 'Invalid cricket target';
    end if;

    v_current := coalesce((v_own_marks->>v_key)::integer, 0);
    v_opp := coalesce((v_opp_marks->>v_key)::integer, 0);
    v_close := least(v_mult, greatest(3 - v_current, 0));
    v_extra := v_mult - v_close;
    v_own_marks := jsonb_set(v_own_marks, array[v_key], to_jsonb(least(3, v_current + v_mult)), true);
    if v_extra > 0 and v_opp < 3 then
      v_points := v_points + (v_extra * v_value);
      v_points_scored := v_points_scored + (v_extra * v_value);
    end if;
  end loop;

  v_all_closed :=
    coalesce((v_own_marks->>'20')::integer,0) >= 3 and coalesce((v_own_marks->>'19')::integer,0) >= 3 and
    coalesce((v_own_marks->>'18')::integer,0) >= 3 and coalesce((v_own_marks->>'17')::integer,0) >= 3 and
    coalesce((v_own_marks->>'16')::integer,0) >= 3 and coalesce((v_own_marks->>'15')::integer,0) >= 3 and
    coalesce((v_own_marks->>'B')::integer,0) >= 3;
  v_leg_won := v_all_closed and v_points >= v_opp_points;

  select coalesce(max(visit_no),0) + 1 into v_visit_no
  from public.cricket_visits
  where match_id = p_match_id and player_id = auth.uid() and leg_no = v_match.current_leg;

  insert into public.cricket_visits(match_id, player_id, leg_no, visit_no, darts, points_scored)
  values (p_match_id, auth.uid(), v_match.current_leg, v_visit_no, p_darts, v_points_scored);

  if v_is_p1 then
    update public.cricket_match_state set player1_marks = v_own_marks, updated_at = now() where match_id = p_match_id;
  else
    update public.cricket_match_state set player2_marks = v_own_marks, updated_at = now() where match_id = p_match_id;
  end if;

  if v_leg_won then
    v_new_legs := (case when v_is_p1 then v_match.player1_legs else v_match.player2_legs end) + 1;
    v_needed := floor(v_match.legs::numeric / 2)::integer + 1;
    if v_new_legs >= v_needed then
      update public.matches
      set player1_score = case when v_is_p1 then v_points else v_match.player1_score end,
          player2_score = case when v_is_p1 then v_match.player2_score else v_points end,
          player1_legs = case when v_is_p1 then v_new_legs else v_match.player1_legs end,
          player2_legs = case when v_is_p1 then v_match.player2_legs else v_new_legs end,
          status='finished', winner_id=auth.uid(), finished_at=now(), updated_at=now()
      where id=p_match_id;
    else
      v_next_starter := case when coalesce(v_match.match_starter_id,v_match.player1_id)=v_match.player1_id then v_match.player2_id else v_match.player1_id end;
      update public.cricket_match_state set player1_marks=v_empty_marks, player2_marks=v_empty_marks, updated_at=now() where match_id=p_match_id;
      update public.matches
      set player1_score=0, player2_score=0,
          player1_legs=case when v_is_p1 then v_new_legs else v_match.player1_legs end,
          player2_legs=case when v_is_p1 then v_match.player2_legs else v_new_legs end,
          current_leg=v_match.current_leg+1, match_starter_id=v_next_starter, turn_player_id=v_next_starter, updated_at=now()
      where id=p_match_id;
    end if;
  else
    update public.matches
    set player1_score=case when v_is_p1 then v_points else v_match.player1_score end,
        player2_score=case when v_is_p1 then v_match.player2_score else v_points end,
        turn_player_id=v_other, updated_at=now()
    where id=p_match_id;
  end if;

  return jsonb_build_object('leg_won',v_leg_won,'points_scored',v_points_scored);
end;
$$;

revoke execute on function public.submit_cricket_visit(uuid,jsonb) from public, anon;
grant execute on function public.submit_cricket_visit(uuid,jsonb) to authenticated;

commit;
