-- JDC Challenge: validated 57-dart training results and leaderboard.

create table if not exists public.jdc_challenge_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  score integer not null check (score between 0 and 3380),
  phase1_score integer not null check (phase1_score between 0 and 1050),
  doubles_score integer not null check (doubles_score between 0 and 1100),
  phase3_score integer not null check (phase3_score between 0 and 1230),
  doubles_hit smallint not null check (doubles_hit between 0 and 21),
  shanghai_count smallint not null check (shanghai_count between 0 and 12),
  badge text not null check (badge in ('white','purple','yellow','green','blue','red','black','gold')),
  hits jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.jdc_challenge_results enable row level security;

drop policy if exists "Authenticated can read JDC results" on public.jdc_challenge_results;
create policy "Authenticated can read JDC results"
on public.jdc_challenge_results
for select
to authenticated
using (true);

revoke insert, update, delete on public.jdc_challenge_results from anon, authenticated;
grant select on public.jdc_challenge_results to authenticated;

create or replace function public.submit_jdc_challenge(p_hits text[])
returns public.jdc_challenge_results
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_idx integer := 1;
  v_target integer;
  v_code text;
  v_phase1 integer := 0;
  v_doubles integer := 0;
  v_phase3 integer := 0;
  v_doubles_hit integer := 0;
  v_shanghai integer := 0;
  v_has_s boolean;
  v_has_d boolean;
  v_has_t boolean;
  v_score integer;
  v_badge text;
  v_row public.jdc_challenge_results;
begin
  if v_user is null then raise exception 'Not authenticated'; end if;
  if coalesce(array_length(p_hits,1),0) <> 57 then raise exception 'JDC Challenge requires exactly 57 darts'; end if;

  for v_target in 10..15 loop
    v_has_s := false; v_has_d := false; v_has_t := false;
    for j in 1..3 loop
      v_code := upper(coalesce(p_hits[v_idx],'')); v_idx := v_idx + 1;
      if v_code = 'M' then null;
      elsif v_code = 'S' then v_phase1 := v_phase1 + v_target; v_has_s := true;
      elsif v_code = 'D' then v_phase1 := v_phase1 + (v_target*2); v_has_d := true;
      elsif v_code = 'T' then v_phase1 := v_phase1 + (v_target*3); v_has_t := true;
      else raise exception 'Invalid Shanghai hit code';
      end if;
    end loop;
    if v_has_s and v_has_d and v_has_t then v_phase1 := v_phase1 + 100; v_shanghai := v_shanghai + 1; end if;
  end loop;

  for v_target in 1..20 loop
    v_code := upper(coalesce(p_hits[v_idx],'')); v_idx := v_idx + 1;
    if v_code = 'M' then null;
    elsif v_code = 'H' then v_doubles := v_doubles + 50; v_doubles_hit := v_doubles_hit + 1;
    else raise exception 'Invalid doubles hit code';
    end if;
  end loop;

  v_code := upper(coalesce(p_hits[v_idx],'')); v_idx := v_idx + 1;
  if v_code = 'M' then null;
  elsif v_code = 'H' then v_doubles := v_doubles + 100; v_doubles_hit := v_doubles_hit + 1;
  else raise exception 'Invalid bull hit code';
  end if;

  for v_target in 15..20 loop
    v_has_s := false; v_has_d := false; v_has_t := false;
    for j in 1..3 loop
      v_code := upper(coalesce(p_hits[v_idx],'')); v_idx := v_idx + 1;
      if v_code = 'M' then null;
      elsif v_code = 'S' then v_phase3 := v_phase3 + v_target; v_has_s := true;
      elsif v_code = 'D' then v_phase3 := v_phase3 + (v_target*2); v_has_d := true;
      elsif v_code = 'T' then v_phase3 := v_phase3 + (v_target*3); v_has_t := true;
      else raise exception 'Invalid Shanghai hit code';
      end if;
    end loop;
    if v_has_s and v_has_d and v_has_t then v_phase3 := v_phase3 + 100; v_shanghai := v_shanghai + 1; end if;
  end loop;

  v_score := v_phase1 + v_doubles + v_phase3;
  v_badge := case
    when v_score >= 1250 then 'gold'
    when v_score >= 850 then 'black'
    when v_score >= 700 then 'red'
    when v_score >= 600 then 'blue'
    when v_score >= 450 then 'green'
    when v_score >= 300 then 'yellow'
    when v_score >= 150 then 'purple'
    else 'white'
  end;

  insert into public.jdc_challenge_results(user_id,score,phase1_score,doubles_score,phase3_score,doubles_hit,shanghai_count,badge,hits)
  values(v_user,v_score,v_phase1,v_doubles,v_phase3,v_doubles_hit,v_shanghai,v_badge,to_jsonb(p_hits))
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.submit_jdc_challenge(text[]) from public, anon;
grant execute on function public.submit_jdc_challenge(text[]) to authenticated;

create or replace view public.jdc_challenge_best
with (security_invoker = true)
as
select distinct on (r.user_id)
  r.user_id,
  p.username,
  r.score as best_score,
  r.phase1_score,
  r.doubles_score,
  r.phase3_score,
  r.doubles_hit,
  r.shanghai_count,
  r.badge,
  r.created_at as achieved_at
from public.jdc_challenge_results r
join public.profiles p on p.id=r.user_id
order by r.user_id, r.score desc, r.created_at asc;

grant select on public.jdc_challenge_best to authenticated;
revoke all on public.jdc_challenge_best from anon;

create or replace function public.admin_delete_jdc_result(p_result_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null or not public.is_admin() then raise exception 'Admin required'; end if;
  delete from public.jdc_challenge_results where id=p_result_id;
end;
$$;

revoke all on function public.admin_delete_jdc_result(bigint) from public, anon;
grant execute on function public.admin_delete_jdc_result(bigint) to authenticated;
