(()=>{
const $=id=>document.getElementById(id),wait=setInterval(()=>{if(!window.supabase||!$('matchView'))return;clearInterval(wait);boot()},100);
async function boot(){
 const matchId=new URLSearchParams(location.search).get('id');if(!matchId)return;
 const db=window.supabase.createClient('https://jqpxlbhwvskhjbqrbidk.supabase.co','sb_publishable_aqx1Q36C3cznImJ5KMDk3w_I1uUTHQK');
 const {data:{session}}=await db.auth.getSession();if(!session)return;const me=session.user.id;
 let {data:match}=await db.from('matches').select('*').eq('id',matchId).single();if(!match)return;let throws=[];
 const host=document.querySelector('.score-card');if(!host)return;
 const box=document.createElement('div');box.className='throw-log';box.innerHTML='<div class="throw-log-head"><strong>Kast i dette leget</strong><small>Kun dine 3 siste kan korrigeres</small></div><div id="throwLogRows"></div>';host.appendChild(box);
 const style=document.createElement('style');style.textContent='.throw-log{margin-top:20px;padding-top:16px;border-top:1px solid rgba(255,255,255,.1)}.throw-log-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:10px}.throw-log-head small{opacity:.65}.throw-row{display:grid;grid-template-columns:minmax(90px,1fr) auto auto;gap:10px;align-items:center;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.06)}.throw-row .throw-score{font-size:1.15rem;font-weight:800}.throw-row button{padding:6px 10px}.throw-row.mine{background:rgba(255,255,255,.025)}.throw-empty{opacity:.55;padding:12px 0}@media(max-width:600px){.throw-log-head{align-items:flex-start;flex-direction:column}.throw-row{grid-template-columns:1fr auto auto}}';document.head.appendChild(style);
 async function load(){const setNo=Number(match.current_set||1),legNo=Number(match.current_leg||1);const {data}=await db.from('match_throws').select('*').eq('match_id',matchId).eq('set_no',setNo).eq('leg_no',legNo).order('created_at',{ascending:true});throws=data||[];draw()}
 function draw(){const el=$('throwLogRows');if(!throws.length){el.innerHTML='<div class="throw-empty">Ingen kast registrert ennå.</div>';return}const mine=throws.filter(t=>t.player_id===me),editable=new Set(mine.slice(-3).map(t=>t.id));el.innerHTML='';throws.forEach(t=>{const row=document.createElement('div');row.className='throw-row'+(t.player_id===me?' mine':'');const who=document.createElement('span');who.textContent=t.player_id===me?'Deg':'Motstander';const score=document.createElement('span');score.className='throw-score';score.textContent=t.is_checkout?`${t.score} (${t.darts_used}p)`:String(t.score);const action=document.createElement('span');if(editable.has(t.id)){const b=document.createElement('button');b.className='outline';b.textContent='Korriger';b.onclick=()=>editThrow(t);action.appendChild(b)}row.append(who,score,action);el.appendChild(row)})}
 async function editThrow(t){const raw=prompt('Ny score (0–180):',String(t.score));if(raw===null)return;const score=Number(raw);if(!Number.isInteger(score)||score<0||score>180){alert('Score må være 0–180.');return}const mine=throws.filter(x=>x.player_id===me),allowed=mine.slice(-3).some(x=>x.id===t.id);if(!allowed){alert('Bare dine tre siste kast i aktivt leg kan korrigeres.');return}const {error}=await db.from('match_throws').update({score,updated_at:new Date().toISOString()}).eq('id',t.id).eq('player_id',me);if(error){alert(error.message);return}await load()}
 db.channel('throw-log-'+matchId).on('postgres_changes',{event:'*',schema:'public',table:'match_throws',filter:`match_id=eq.${matchId}`},()=>load()).on('postgres_changes',{event:'UPDATE',schema:'public',table:'matches',filter:`id=eq.${matchId}`},p=>{const oldSet=match.current_set,oldLeg=match.current_leg;match=p.new;if(oldSet!==match.current_set||oldLeg!==match.current_leg)load()}).subscribe();
 await load();
 window.DartArenaThrowLog={async record(score,dartsUsed=3,isCheckout=false){const setNo=Number(match.current_set||1),legNo=Number(match.current_leg||1);const {count}=await db.from('match_throws').select('*',{count:'exact',head:true}).eq('match_id',matchId).eq('player_id',me).eq('set_no',setNo).eq('leg_no',legNo);const visitNo=Number(count||0)+1;return db.from('match_throws').insert({match_id:matchId,player_id:me,set_no:setNo,leg_no:legNo,visit_no:visitNo,score,darts_used:dartsUsed,is_checkout:isCheckout})}};
}
})();