(()=>{
const $=id=>document.getElementById(id);let db,me,profile,channel;
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(d){try{return new Intl.DateTimeFormat('nb-NO',{dateStyle:'short',timeStyle:'short'}).format(new Date(d))}catch{return d}}
async function boot(){if(!window.supabase||!$('tournamentList'))return;db=window.supabase.createClient('https://jqpxlbhwvskhjbqrbidk.supabase.co','sb_publishable_aqx1Q36C3cznImJ5KMDk3w_I1uUTHQK');const {data:{session}}=await db.auth.getSession();if(!session)return;me=session.user.id;const {data:p}=await db.from('profiles').select('id,username').eq('id',me).single();profile=p;bind();await load();channel=db.channel('tournament-lobby').on('postgres_changes',{event:'*',schema:'public',table:'tournaments'},load).on('postgres_changes',{event:'*',schema:'public',table:'tournament_members'},load).subscribe()}
function bind(){$('createTournamentBtn').onclick=()=>{$('tournamentModal').classList.remove('hidden');const d=new Date(Date.now()+3600000);d.setMinutes(Math.ceil(d.getMinutes()/5)*5,0,0);$('tournamentStart').value=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')+'T'+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')};$('closeTournamentModal').onclick=()=>$('tournamentModal').classList.add('hidden');$('tournamentModalBackdrop').onclick=()=>$('tournamentModal').classList.add('hidden');$('createTournamentForm').onsubmit=create}
async function create(e){e.preventDefault();const name=$('tournamentName').value.trim(),type=$('tournamentType').value,start=$('tournamentStart').value,msg=$('tournamentCreateMessage');msg.textContent='Oppretter…';const {data,error}=await db.from('tournaments').insert({name,owner_id:me,tournament_type:type,starts_at:new Date(start).toISOString()}).select('*').single();if(error){msg.textContent=error.message;msg.className='message error';return}msg.textContent='';$('tournamentModal').classList.add('hidden');await load();location.href=`tournament.html?id=${encodeURIComponent(data.id)}`}
async function load(){const {data:t,error}=await db.from('tournaments').select('*').neq('status','cancelled').order('starts_at',{ascending:true});if(error){$('tournamentList').innerHTML='<p class="muted">Kjør tournament-SQL først.</p>';return}const ids=(t||[]).map(x=>x.id);let members=[];if(ids.length){const r=await db.from('tournament_members').select('tournament_id,user_id,role').in('tournament_id',ids);members=r.data||[]}const counts={};members.forEach(m=>{(counts[m.tournament_id]??=[]).push(m)});$('tournamentList').innerHTML=t?.length?t.map(x=>{const list=counts[x.id]||[],joined=list.some(m=>m.user_id===me),owner=x.owner_id===me,n=list.filter(m=>m.role==='participant').length;return `<article class="tournament-row"><div><div class="player-name">${esc(x.name)}</div><div class="status">${x.tournament_type==='groups_cup'?'Puljer + cup':'Ren cup'} • ${fmt(x.starts_at)} • ${n} påmeldt</div></div><div class="challenge-actions"><button class="small-btn" data-open="${x.id}">Åpne</button>${x.registration_open&&!owner?`<button class="small-btn ${joined?'decline':'accept'}" data-${joined?'leave':'join'}="${x.id}">${joined?'Avmeld':'Meld på'}</button>`:''}</div></article>`}).join(''):'<p class="muted">Ingen turneringer opprettet ennå.</p>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>location.href=`tournament.html?id=${encodeURIComponent(b.dataset.open)}`);document.querySelectorAll('[data-join]').forEach(b=>b.onclick=()=>join(b.dataset.join));document.querySelectorAll('[data-leave]').forEach(b=>b.onclick=()=>leave(b.dataset.leave))}
async function join(id){const {error}=await db.from('tournament_members').insert({tournament_id:id,user_id:me,role:'participant'});if(error)alert(error.message);else load()}
async function leave(id){const {error}=await db.from('tournament_members').delete().eq('tournament_id',id).eq('user_id',me);if(error)alert(error.message);else load()}
const wait=setInterval(()=>{if(window.supabase&&$('tournamentList')){clearInterval(wait);boot()}},100);
})();