(()=>{
const $=id=>document.getElementById(id);let db,me,profile,channel,viewMonth,selectedDate,selectedTime='19:00';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(d){try{return new Intl.DateTimeFormat('nb-NO',{dateStyle:'short',timeStyle:'short'}).format(new Date(d))}catch{return d}}
function pad(n){return String(n).padStart(2,'0')}function localValue(d,time){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${time}`}
function pretty(d,time){if(!d)return'Velg dato og klokkeslett';const day=new Intl.DateTimeFormat('nb-NO',{weekday:'short',day:'2-digit',month:'short'}).format(d).replace('.','').toUpperCase();return `${day} · ${time}`}
async function boot(){if(!window.supabase||!$('tournamentList'))return;db=window.supabase.createClient('https://jqpxlbhwvskhjbqrbidk.supabase.co','sb_publishable_aqx1Q36C3cznImJ5KMDk3w_I1uUTHQK');const {data:{session}}=await db.auth.getSession();if(!session)return;me=session.user.id;const {data:p}=await db.from('profiles').select('id,username').eq('id',me).single();profile=p;bind();await load();channel=db.channel('tournament-lobby').on('postgres_changes',{event:'*',schema:'public',table:'tournaments'},load).on('postgres_changes',{event:'*',schema:'public',table:'tournament_members'},load).subscribe()}
function defaultDate(){const d=new Date(Date.now()+3600000);d.setMinutes(Math.ceil(d.getMinutes()/5)*5,0,0);selectedDate=new Date(d.getFullYear(),d.getMonth(),d.getDate());selectedTime=`${pad(d.getHours())}:${pad(d.getMinutes())}`;viewMonth=new Date(d.getFullYear(),d.getMonth(),1);syncDate()}
function bind(){$('createTournamentBtn').onclick=()=>{$('tournamentModal').classList.remove('hidden');defaultDate()};$('closeTournamentModal').onclick=()=>$('tournamentModal').classList.add('hidden');$('tournamentModalBackdrop').onclick=()=>$('tournamentModal').classList.add('hidden');$('createTournamentForm').onsubmit=create;$('openDatePicker').onclick=openPicker;$('datePickerBackdrop').onclick=closePicker;$('cancelDatePicker').onclick=closePicker;$('prevMonth').onclick=()=>{viewMonth=new Date(viewMonth.getFullYear(),viewMonth.getMonth()-1,1);renderCalendar()};$('nextMonth').onclick=()=>{viewMonth=new Date(viewMonth.getFullYear(),viewMonth.getMonth()+1,1);renderCalendar()};$('customTime').oninput=e=>{if(e.target.value){selectedTime=e.target.value;renderTimes();updateSummary()}};$('confirmDatePicker').onclick=()=>{syncDate();closePicker()}}
function openPicker(){if(!selectedDate)defaultDate();viewMonth=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1);renderCalendar();renderTimes();updateSummary();$('datePickerModal').classList.remove('hidden')}
function closePicker(){$('datePickerModal').classList.add('hidden')}
function renderCalendar(){const y=viewMonth.getFullYear(),m=viewMonth.getMonth();$('calendarMonth').textContent=new Intl.DateTimeFormat('nb-NO',{month:'long',year:'numeric'}).format(viewMonth);const first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),today=new Date();let html='';for(let i=0;i<first;i++)html+='<span class="calendar-empty"></span>';for(let d=1;d<=days;d++){const dt=new Date(y,m,d),past=new Date(y,m,d+1)<=new Date(today.getFullYear(),today.getMonth(),today.getDate()),sel=selectedDate&&dt.toDateString()===selectedDate.toDateString(),isToday=dt.toDateString()===today.toDateString();html+=`<button type="button" class="calendar-day${sel?' selected':''}${isToday?' today':''}" data-day="${d}" ${past?'disabled':''}>${d}</button>`}$('calendarDays').innerHTML=html;document.querySelectorAll('.calendar-day:not(:disabled)').forEach(b=>b.onclick=()=>{selectedDate=new Date(y,m,Number(b.dataset.day));renderCalendar();updateSummary()})}
function renderTimes(){const times=['17:00','17:30','18:00','18:30','19:00','19:30','20:00','20:30','21:00'];$('quickTimes').innerHTML=times.map(t=>`<button type="button" class="time-chip${selectedTime===t?' selected':''}" data-time="${t}">${t}</button>`).join('');document.querySelectorAll('.time-chip').forEach(b=>b.onclick=()=>{selectedTime=b.dataset.time;$('customTime').value='';renderTimes();updateSummary()})}
function updateSummary(){$('datePickerSummary').textContent=selectedDate?pretty(selectedDate,selectedTime):'Velg dato og tid'}function syncDate(){if(!selectedDate)return;$('tournamentStart').value=localValue(selectedDate,selectedTime);$('dateTimeText').textContent=pretty(selectedDate,selectedTime)}
async function create(e){e.preventDefault();const name=$('tournamentName').value.trim(),type=$('tournamentType').value,start=$('tournamentStart').value,msg=$('tournamentCreateMessage');if(!start){msg.textContent='Velg starttidspunkt.';msg.className='message error';return}msg.textContent='Oppretter…';const {data,error}=await db.from('tournaments').insert({name,owner_id:me,tournament_type:type,starts_at:new Date(start).toISOString()}).select('*').single();if(error){msg.textContent=error.message;msg.className='message error';return}msg.textContent='';$('tournamentModal').classList.add('hidden');await load();location.href=`tournament.html?id=${encodeURIComponent(data.id)}`}
async function load(){const {data:t,error}=await db.from('tournaments').select('*').neq('status','cancelled').order('starts_at',{ascending:true});if(error){$('tournamentList').innerHTML='<p class="muted">Kjør tournament-SQL først.</p>';return}const ids=(t||[]).map(x=>x.id);let members=[];if(ids.length){const r=await db.from('tournament_members').select('tournament_id,user_id,role').in('tournament_id',ids);members=r.data||[]}const counts={};members.forEach(m=>{(counts[m.tournament_id]??=[]).push(m)});$('tournamentList').innerHTML=t?.length?t.map(x=>{const list=counts[x.id]||[],joined=list.some(m=>m.user_id===me),n=list.filter(m=>m.role==='participant').length;return `<article class="tournament-row"><div><div class="player-name">${esc(x.name)}</div><div class="status">${x.tournament_type==='groups_cup'?'Puljer + cup':'Ren cup'} • ${fmt(x.starts_at)} • ${n} påmeldt</div></div><div class="challenge-actions"><button class="small-btn" data-open="${x.id}">Åpne</button>${x.registration_open?`<button class="small-btn ${joined?'decline':'accept'}" data-${joined?'leave':'join'}="${x.id}">${joined?'Avmeld':'Meld på'}</button>`:''}</div></article>`}).join(''):'<p class="muted">Ingen turneringer opprettet ennå.</p>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>location.href=`tournament.html?id=${encodeURIComponent(b.dataset.open)}`);document.querySelectorAll('[data-join]').forEach(b=>b.onclick=()=>join(b.dataset.join));document.querySelectorAll('[data-leave]').forEach(b=>b.onclick=()=>leave(b.dataset.leave))}
async function join(id){const {error}=await db.from('tournament_members').insert({tournament_id:id,user_id:me,role:'participant'});if(error)alert(error.message);else load()}async function leave(id){const {error}=await db.from('tournament_members').delete().eq('tournament_id',id).eq('user_id',me);if(error)alert(error.message);else load()}
const wait=setInterval(()=>{if(window.supabase&&$('tournamentList')){clearInterval(wait);boot()}},100);
})();